import { stores } from "./network";
import type { Store } from "./types";

export type JourneyStage = {
  id: string;
  n: string;
  title: string;
  blurb: string;
  storeIds: string[];
  guideHref?: string;
  search?: string;
  finds?: string[];
};

function pick(ids: string[]): Store[] {
  return ids
    .map((id) => stores.find((s) => s.id === id))
    .filter((s): s is Store => Boolean(s));
}

export const journeyStages: JourneyStage[] = [
  {
    id: "engagement",
    n: "01",
    title: "الخطوبة",
    blurb: "ذهب، دبل، هدايا بسيطة — من الصاغة للمولات.",
    storeIds: ["sogha", "damas", "azzafahmy", "pandora", "swarovski", "giftshops", "jumia", "noon"],
    search: "طقم زركون",
    finds: ["شبكات", "دبل", "هدايا خطوبة"],
  },
  {
    id: "wedding-dress",
    n: "02",
    title: "فستان الفرح",
    blurb: "بوتيكات متخصصة. السعر والمقاس على الطبيعة؛ وفّري بتلمّ المصدر مش بتبيع الفستان.",
    storeIds: [
      "vero-bridal",
      "mariage",
      "lanovia",
      "moller",
      "vogue-bridal",
      "glamour-dalia",
      "chantelle",
      "whiteveil",
      "malton",
    ],
    search: "فستان فرح",
    finds: ["فساتين زفاف", "طرح", "تعديل مقاس"],
  },
  {
    id: "bridal-acc",
    n: "03",
    title: "إكسسوار العروسة",
    blurb: "طرح، تيجان، إكسسوار شعر، شنط قاعة.",
    storeIds: ["swarovski", "pandora", "whiteveil", "namshi", "sixthstreet", "jumia", "noon"],
    search: "إكسسوار",
    finds: ["إكسسوار شعر", "كلتش", "طرح فرح"],
  },
  {
    id: "beauty",
    n: "04",
    title: "تجميل ومكياج",
    blurb: "من سيفورا للعزبي وجوميا: مكياج، عطور، أدوات.",
    storeIds: [
      "sephora",
      "faces",
      "mazaya",
      "eva",
      "orchidia",
      "elezaby",
      "p19011",
      "beautymarket",
      "goldenscent",
      "seif",
      "jumia",
      "noon",
    ],
    guideHref: "/guide#beauty",
    search: "ميكب",
    finds: ["مكياج", "عطور", "فرش", "مثبت"],
  },
  {
    id: "skincare",
    n: "05",
    title: "عناية بشرة وشعر",
    blurb: "غسول، سيروم، واقي شمس، شامبو، ماسك — صيدليات وهايبر وماركتبليس.",
    storeIds: [
      "elezaby",
      "p19011",
      "seif",
      "carrefour",
      "spinneys",
      "sephora",
      "faces",
      "jumia",
      "noon",
    ],
    guideHref: "/guide#beauty",
    search: "غسول وجه",
    finds: ["بشرة", "شعر", "واقي شمس", "عناية أنثوية", "فم"],
  },
  {
    id: "lingerie",
    n: "06",
    title: "لانجري",
    blurb: "سلاسل المولات + كوتونيل + بوتيكات إنستجرام المحلية.",
    storeIds: ["nayomi", "lasenza", "triumph", "cottonil", "ig-lingerie", "namshi", "jumia"],
    guideHref: "/guide#wardrobe",
    search: "لانجري",
    finds: ["لانجري شهر العسل", "داخلي قطن"],
  },
  {
    id: "clothes",
    n: "07",
    title: "الملابس",
    blurb: "خروج وبيت: إل سي واكيك لديفاكتو لزارا لكوتونيل.",
    storeIds: [
      "lcw",
      "defacto",
      "hm",
      "zara",
      "mango",
      "max",
      "randb",
      "cottonil",
      "concrete",
      "mobaco",
      "townteam",
      "dalydress",
      "namshi",
      "sixthstreet",
    ],
    guideHref: "/guide#wardrobe",
    search: "بيجاما",
    finds: ["خروج", "بيت", "تريننج", "مناسبات"],
  },
  {
    id: "shoes-bags",
    n: "08",
    title: "أحذية وشنط",
    blurb: "مولات الجلد المحلي + ألدو وتشارلز آند كيث.",
    storeIds: ["bata", "aldo", "ck", "shoemart", "ninewest", "leather-local", "defacto", "namshi"],
    search: "شباشب",
    finds: ["خروج", "قاعة", "شنط يد", "جلد محلي"],
  },
  {
    id: "honeymoon",
    n: "09",
    title: "شهر العسل",
    blurb: "شنط سفر، بيتشوير، منظمات، باور بانك.",
    storeIds: [
      "amtourister",
      "samsonite",
      "jumia",
      "noon",
      "amazon",
      "aldo",
      "lcw",
      "hm",
      "defacto",
    ],
    guideHref: "/guide#travel",
    search: "شنط سفر",
    finds: ["شنط", "بيتشوير", "لانجري سفر", "منظمات"],
  },
  {
    id: "appliances",
    n: "10",
    title: "أجهزة البيت",
    blurb: "رنين، بي تك، العربي، 2B، راية، فريش، عبدالعزيز والعتبة للمقارنة على الطبيعة.",
    storeIds: [
      "raneen",
      "cairosales",
      "gaballah",
      "abdelaziz",
      "ataba",
      "tawhid-nour",
      "btech",
      "elaraby",
      "twob",
      "raya",
      "fresh",
      "zanussi-eg",
      "samsung",
      "lgshop",
      "boschshop",
      "tornado",
      "jumia",
      "noon",
    ],
    guideHref: "/guide#electrical",
    search: "غسالة",
    finds: ["ثلاجة", "بوتاجاز", "تكييف", "غسالة"],
  },
  {
    id: "kitchen",
    n: "11",
    title: "المطبخ (أجهزة)",
    blurb: "بوتاجاز، شفاط، ميكروويف، قلاية — سلاسل + هايبر.",
    storeIds: ["btech", "raneen", "carrefour", "jumia", "noon", "fresh", "tornado"],
    guideHref: "/guide#electrical",
    search: "بوتاجاز",
  },
  {
    id: "kitchenware",
    n: "12",
    title: "رفايع المطبخ",
    blurb: "حمام التلات والعتبة وشبرا والنزهة: أرخص تنوع لأطقم الطهي والتقديم.",
    storeIds: [
      "hammam-tlat",
      "ataba",
      "darb-saada",
      "shubra",
      "nozha",
      "moski",
      "bab-shareya",
      "azhar-housewares",
      "ikea",
      "carrefour",
      "jumia",
      "noon",
    ],
    guideHref: "/guide#kitchen",
    search: "طقم حلل",
    finds: ["حلل", "طاسات", "أطباق", "علب", "سكاكين"],
  },
  {
    id: "bedding",
    n: "13",
    title: "المفروشات",
    blurb: "ايكيا، هوم سنتر، موبيكا، النزهة والعتبة وشبرا.",
    storeIds: [
      "ikea",
      "homecentre",
      "hm-home",
      "mobica",
      "ashley",
      "townteam",
      "lacasa",
      "nozha",
      "ataba",
      "shubra",
      "homzmart",
    ],
    guideHref: "/guide#bedroom",
    search: "لحاف",
    finds: ["ملايات", "لحاف", "فوط", "ستائر"],
  },
  {
    id: "bathroom",
    n: "14",
    title: "الحمام",
    blurb: "ستائر ودواسات ومنظمات من ايكيا والهايبر والرفايع.",
    storeIds: ["ikea", "homecentre", "carrefour", "jumia", "noon", "hammam-tlat"],
    guideHref: "/guide#bathroom",
    search: "ستارة حمام",
  },
  {
    id: "cleaning",
    n: "15",
    title: "التنظيف",
    blurb: "كارفور، هايبر وان، مترو، كازيون، رنين، ايكيا.",
    storeIds: [
      "jumia",
      "noon",
      "carrefour",
      "hyperone",
      "metro",
      "kazyon",
      "raneen",
      "ikea",
      "homecentre",
      "hammam-tlat",
    ],
    guideHref: "/guide#cleaning",
    search: "ممسحة",
  },
  {
    id: "organization",
    n: "16",
    title: "التنظيم والتخزين",
    blurb: "كاتيجوري تقدر تبقى بيزنس لوحدها: منظمات أدراج ودولاب وشنط تفريغ.",
    storeIds: ["ikea", "homecentre", "jumia", "noon", "amazon", "homzmart", "miniso", "hammam-tlat"],
    guideHref: "/guide#storage",
    search: "منظم",
    finds: ["أدراج", "دولاب", "أحذية", "مكنسة أكياس تفريغ"],
  },
  {
    id: "decor",
    n: "17",
    title: "ديكور البيت",
    blurb: "ايكيا، هوم سنتر، هومزمارت، دمياط للأثاث الثقيل.",
    storeIds: [
      "ikea",
      "homecentre",
      "hm-home",
      "miniso",
      "jumia",
      "noon",
      "homzmart",
      "damietta",
      "thehome",
      "potterybarn",
      "cityfurniture",
    ],
    guideHref: "/guide#decor",
    search: "سجاد",
  },
  {
    id: "dining",
    n: "18",
    title: "السفرة والتقديم",
    blurb: "أطباق وكاسات وصواني — ايكيا + حمام التلات + الهايبر.",
    storeIds: ["ikea", "homecentre", "carrefour", "jumia", "noon", "hammam-tlat", "ataba"],
    guideHref: "/guide#tableware",
    search: "طقم أطباق",
  },
  {
    id: "fragrance",
    n: "19",
    title: "عطور البيت",
    blurb: "شموع، ديفيوزر، بخاخ جو.",
    storeIds: ["ikea", "homecentre", "hm-home", "miniso", "jumia", "noon", "homzmart"],
    guideHref: "/guide#decor",
    search: "شموع",
  },
  {
    id: "gifts",
    n: "20",
    title: "الهدايا",
    blurb: "ميني سو، ورد، شوكولاتة، عطور — لهدايا الخطوبة والجواز.",
    storeIds: ["miniso", "jumia", "noon", "amazon", "giftshops", "goldenscent", "sogha"],
    search: "هدية",
  },
  {
    id: "emergency",
    n: "21",
    title: "طوارئ ومتفرقات",
    blurb: "صيدليات + عدة صغيرة + رفايع بتتنسي.",
    storeIds: ["elezaby", "p19011", "seif", "ace", "jumia", "carrefour"],
    guideHref: "/guide#emergency",
    search: "ترمومتر",
  },
];

export const oneStopIds = [
  "sednawy",
  "citystyle",
  "jumia",
  "noon",
  "amazon",
  "carrefour",
  "hyperone",
  "spinneys",
  "kazyon",
  "metro",
  "tawhid-nour",
];

export function storesForStage(stage: JourneyStage) {
  return pick(stage.storeIds);
}

export function oneStopStores() {
  return pick(oneStopIds);
}
