import type { CategoryId, Product } from "./types";
import { makeSku } from "./sku-factory";

export type GuideItem = {
  productId: string;
  name: string;
  existing?: boolean;
  brand?: string;
  category?: CategoryId;
  price?: number;
  hint?: string;
};

export type GuideSection = {
  id: string;
  title: string;
  blurb: string;
  commercial: string;
  items: GuideItem[];
};

function n(
  productId: string,
  name: string,
  brand: string,
  category: CategoryId,
  price: number,
  hint: string,
): GuideItem {
  return { productId, name, brand, category, price, hint };
}

function ex(productId: string, name: string): GuideItem {
  return { productId, name, existing: true };
}

export const brideSections: GuideSection[] = [
  {
    id: "kitchen",
    title: "تجهيز المطبخ",
    commercial: "Kitchen Essentials",
    blurb: "من أطقم الحلل لأصغر رفايع الدرج: كل اللي بيشتغل في أول بيت.",
    items: [
      ex("tefal-pots", "أطقم حلل"),
      n("br-k-pans", "طاسات", "تيفال", "kitchen-tools", 890, "طقم طاسات مانع التصاق"),
      n("br-k-oven-trays", "صواني فرن", "بريستيج", "kitchen-tools", 420, "صواني فرن معدنية"),
      n("br-k-serve-trays", "صواني تقديم", "ايكيا", "kitchen-tools", 340, "صواني تقديم للسفرة"),
      n("br-k-granite", "طقم جرانيت", "جرانيت برو", "kitchen-tools", 2190, "طقم جرانيت ثقيل"),
      n("br-k-ceramic", "طقم سيراميك", "سيرافيت", "kitchen-tools", 1650, "حلل سيراميك"),
      n("br-k-pressure", "حلة ضغط", "سيفك", "kitchen-tools", 1890, "حلة ضغط ستانلس"),
      n("br-k-milk-pot", "حلة لبن", "تيفال", "kitchen-tools", 280, "حلة لبن بمصب"),
      n("br-k-coffee-pot", "كنكة قهوة", "إمبريال", "kitchen-tools", 190, "كنكة قهوة تركي"),
      n("br-k-tea-pot-small", "كنكة شاي", "إمبريال", "kitchen-tools", 160, "كنكة شاي صغيرة"),
      n("br-k-teapot", "براد شاي", "زازا", "kitchen-tools", 390, "براد شاي ستانلس"),
      ex("kettle-kenwood", "غلاية مياه"),
      n("br-k-spoons", "طقم معالق", "وينسلو", "kitchen-tools", 220, "طقم معالق سفرة"),
      n("br-k-forks", "طقم شوك", "وينسلو", "kitchen-tools", 220, "طقم شوك سفرة"),
      n("br-k-knives-set", "طقم سكاكين", "وينسلو", "kitchen-tools", 240, "طقم سكاكين سفرة"),
      n("br-k-chef-knives", "سكاكين تقطيع", "تيفال", "kitchen-tools", 560, "طقم سكاكين شيف"),
      n("br-k-bread-knife", "سكينة خبز", "تيفال", "kitchen-tools", 180, "سكينة خبز مسننة"),
      n("br-k-board", "لوح تقطيع", "ايكيا", "kitchen-tools", 150, "لوح تقطيع خشب"),
      n("br-k-shears", "مقص مطبخ", "ايكيا", "kitchen-tools", 95, "مقص دواجن ومطبخ"),
      n("br-k-colander", "مصفاة", "ايكيا", "kitchen-tools", 85, "مصفاة استانلس"),
      n("br-k-rice-strainer", "مصفاة أرز", "ايكيا", "kitchen-tools", 70, "مصفاة أرز ناعمة"),
      n("br-k-grater", "مبشرة", "تيفال", "kitchen-tools", 90, "مبشرة 4 أوجه"),
      n("br-k-masher", "هراسة بطاطس", "ايكيا", "kitchen-tools", 65, "هراسة بطاطس ستانلس"),
      n("br-k-can-opener", "فتاحة علب", "ايكيا", "kitchen-tools", 55, "فتاحة علب يدوية"),
      n("br-k-bottle-opener", "فتاحة زجاجات", "ايكيا", "kitchen-tools", 40, "فتاحة زجاجات"),
      n("br-k-lemon", "عصارة ليمون", "ايكيا", "kitchen-tools", 45, "عصارة ليمون يدوية"),
      n("br-k-whisk-hand", "مضرب بيض", "ايكيا", "kitchen-tools", 50, "مضرب بيض يدوي"),
      n("br-k-whisk-wire", "مضرب سلك", "ايكيا", "kitchen-tools", 40, "مضرب سلك"),
      n("br-k-wood-spoons", "ملاعق خشب", "ايكيا", "kitchen-tools", 75, "طقم ملاعق خشب"),
      n("br-k-silicone", "ملاعق سيليكون", "تيفال", "kitchen-tools", 120, "طقم سيليكون مقاوم للحرارة"),
      n("br-k-ladles", "مغارف", "تيفال", "kitchen-tools", 110, "مغارف شوربة وسوس"),
      n("br-k-tongs", "ملقاط مطبخ", "تيفال", "kitchen-tools", 70, "ملقاط تقليب"),
      n("br-k-spoon-rest", "حامل ملاعق", "ايكيا", "kitchen-tools", 55, "حامل ملاعق على البوتاجاز"),
      n("br-k-knife-block", "حامل سكاكين", "ايكيا", "kitchen-tools", 180, "حامل سكاكين خشب"),
      n("br-k-spice-rack", "حامل توابل", "ايكيا", "kitchen-tools", 160, "حامل توابل دوار"),
      n("br-k-spice-set", "طقم توابل", "ايكيا", "kitchen-tools", 210, "برطمانات توابل مع رف"),
      n("br-k-jars", "برطمانات تخزين", "لوك آند لوك", "kitchen-tools", 280, "برطمانات زجاج بغطاء"),
      n("br-k-food-boxes", "علب حفظ الطعام", "لوك آند لوك", "kitchen-tools", 320, "علب محكمة"),
      n("br-k-fridge-boxes", "علب ثلاجة", "لوك آند لوك", "kitchen-tools", 240, "علب ثلاجة شفافة"),
      n("br-k-freezer-boxes", "علب فريزر", "لوك آند لوك", "kitchen-tools", 260, "علب فريزر آمنة"),
      n("br-k-zip-bags", "أكياس حفظ الطعام", "كارفور", "kitchen-tools", 45, "أكياس بسحاب"),
      n("br-k-freezer-bags", "أكياس فريزر", "كارفور", "kitchen-tools", 40, "أكياس فريزر سميكة"),
      n("br-k-cling", "رول استرتش", "كارفور", "kitchen-tools", 35, "استرتش طعام"),
      n("br-k-parchment", "ورق زبدة", "كارفور", "kitchen-tools", 40, "ورق زبدة للفرن"),
      n("br-k-foil", "فويل", "كارفور", "kitchen-tools", 38, "فويل ألومنيوم"),
      n("br-k-trash-bags", "أكياس قمامة", "كارفور", "kitchen-tools", 42, "أكياس قمامة للمطبخ"),
      n("br-k-bin", "سلة قمامة", "ايكيا", "kitchen-tools", 190, "سلة قمامة بدواسة"),
      n("br-k-veg-basket", "سلة خضار", "ايكيا", "kitchen-tools", 120, "سلة خضار مهواة"),
      n("br-k-fruit-basket", "سلة فاكهة", "ايكيا", "kitchen-tools", 130, "سلة فاكهة معدنية"),
      n("br-k-drawer-org", "منظم أدراج المطبخ", "ايكيا", "storage", 150, "فواصل أدراج"),
      n("br-k-cupboard-org", "منظم الدولاب", "ايكيا", "storage", 180, "منظم خزائن المطبخ"),
      n("br-k-under-sink", "منظم تحت الحوض", "ايكيا", "storage", 220, "رف تحت الحوض"),
      n("br-k-cup-holder", "حامل أكواب", "ايكيا", "kitchen-tools", 90, "حامل أكواب"),
      n("br-k-dish-rack", "حامل أطباق", "ايكيا", "kitchen-tools", 210, "مجفف أطباق"),
      n("br-k-napkin-stand", "حامل مناديل", "ايكيا", "kitchen-tools", 70, "حامل مناديل مطبخ"),
      n("br-k-sponge-holder", "حامل إسفنجة", "ايكيا", "kitchen-tools", 45, "حامل إسفنجة للحوض"),
      n("br-k-bottle-brush", "فرش تنظيف الزجاجات", "ايكيا", "cleaning", 55, "فرش زجاجات رضّاعة وكاسات"),
      n("br-k-sponges", "إسفنج مواعين", "كارفور", "cleaning", 30, "إسفنج مواعين"),
      n("br-k-scrub", "ليفة مواعين", "كارفور", "cleaning", 25, "ليفة سلك ناعمة"),
      ex("kitchen-linens", "فوطة مطبخ"),
      n("br-k-oven-mitt", "جوانتي فرن", "ايكيا", "kitchen-tools", 80, "جوانتي حراري"),
      n("br-k-apron", "مريلة مطبخ", "ايكيا", "kitchen-tools", 95, "مريلة قطن"),
    ],
  },
  {
    id: "tableware",
    title: "أدوات السفرة والتقديم",
    commercial: "Kitchen Essentials",
    blurb: "أطباق وكاسات وصواني تقدّم العزايم من غير ما تشتري بالقطعة كل مرة.",
    items: [
      n("br-t-dinner-set", "طقم أطباق", "لومينارك", "kitchen-tools", 1890, "طقم عشاء 24 قطعة"),
      n("br-t-flat-plates", "أطباق مسطحة", "لومينارك", "kitchen-tools", 420, "أطباق مسطحة إضافية"),
      n("br-t-deep-plates", "أطباق غويطة", "لومينارك", "kitchen-tools", 390, "أطباق شوربة"),
      n("br-t-dessert-plates", "أطباق حلويات", "لومينارك", "kitchen-tools", 280, "أطباق حلويات"),
      n("br-t-serving-plates", "أطباق تقديم", "لومينارك", "kitchen-tools", 340, "أطباق تقديم كبيرة"),
      n("br-t-glass-set", "طقم كاسات", "لومينارك", "kitchen-tools", 260, "طقم كاسات 12 قطعة"),
      n("br-t-water-glasses", "كاسات مياه", "لومينارك", "kitchen-tools", 180, "كاسات مياه"),
      n("br-t-juice-glasses", "كاسات عصير", "لومينارك", "kitchen-tools", 170, "كاسات عصير"),
      n("br-t-tea-glasses", "كاسات شاي", "لومينارك", "kitchen-tools", 150, "كاسات شاي أركوبال"),
      n("br-t-mugs", "مجات", "ايكيا", "kitchen-tools", 160, "طقم مجات"),
      n("br-t-coffee-cups", "فناجين قهوة", "لومينارك", "kitchen-tools", 220, "فناجين قهوة تركي"),
      n("br-t-tea-cups", "فناجين شاي", "لومينارك", "kitchen-tools", 240, "فناجين شاي بطبق"),
      n("br-t-serving-spoons", "طقم ملاعق تقديم", "وينسلو", "kitchen-tools", 190, "ملاعق تقديم ستانلس"),
      n("br-t-serving-forks", "شوك تقديم", "وينسلو", "kitchen-tools", 160, "شوك تقديم"),
      n("br-t-table-knives", "سكاكين سفرة", "وينسلو", "kitchen-tools", 180, "سكاكين سفرة"),
      n("br-t-tray", "صينية تقديم", "ايكيا", "kitchen-tools", 210, "صينية تقديم خشب"),
      n("br-t-tea-tray", "صينية شاي", "ايكيا", "kitchen-tools", 230, "صينية شاي بمقابض"),
      n("br-t-big-bowl", "بولة كبيرة", "لومينارك", "kitchen-tools", 140, "بولة سلطة كبيرة"),
      n("br-t-small-bowls", "بولات صغيرة", "لومينارك", "kitchen-tools", 160, "طقم بولات"),
      n("br-t-salad-set", "طقم سلطانيات", "لومينارك", "kitchen-tools", 280, "سلطانيات تقديم"),
      n("br-t-fruit-plate", "طبق فاكهة", "لومينارك", "kitchen-tools", 120, "طبق فاكهة"),
      n("br-t-sweet-plate", "طبق حلويات", "لومينارك", "kitchen-tools", 110, "طبق حلويات"),
      n("br-t-cake-plate", "طبق كيك", "لومينارك", "kitchen-tools", 150, "طبق كيك"),
      n("br-t-cake-stand", "حامل كيك", "ايكيا", "kitchen-tools", 190, "حامل كيك بطبقات"),
      n("br-t-water-jug", "إبريق مياه", "لومينارك", "kitchen-tools", 130, "إبريق زجاج"),
      n("br-t-juice-jug", "إبريق عصير", "لومينارك", "kitchen-tools", 140, "إبريق عصير بغطاء"),
      n("br-t-tablecloth", "مفرش سفرة", "ايكيا", "textiles", 220, "مفرش سفرة مقاوم للبقع"),
      n("br-t-runner", "رانر", "ايكيا", "textiles", 140, "رانر سفرة"),
      n("br-t-coasters", "كوسترات", "ايكيا", "kitchen-tools", 60, "طقم كوسترات"),
      n("br-t-napkin-rings", "حلقات مناديل", "ايكيا", "kitchen-tools", 70, "حلقات مناديل سفرة"),
      n("br-t-napkins", "مناديل سفرة", "ايكيا", "textiles", 90, "مناديل قماش للسفرة"),
    ],
  },
  {
    id: "cleaning",
    title: "أدوات التنظيف",
    commercial: "Cleaning",
    blurb: "من المقشة لمنظف الزجاج: بوكس تنظيف يخلّي الشقة تتشال من أول أسبوع.",
    items: [
      n("br-c-broom", "مقشة", "ايكيا", "cleaning", 85, "مقشة ناعمة"),
      n("br-c-dustpan", "جاروف", "ايكيا", "cleaning", 45, "جاروف مع فرشاة"),
      n("br-c-mop", "ممسحة", "ايكيا", "cleaning", 190, "ممسحة ميكروفايبر"),
      n("br-c-bucket", "جردل", "ايكيا", "cleaning", 80, "جردل بعصر"),
      n("br-c-squeegee", "ممسحة زجاج", "ايكيا", "cleaning", 70, "ممسحة شبابيك"),
      n("br-c-steel-wool", "سلك مواعين", "كارفور", "cleaning", 20, "سلك مواعين"),
      n("br-c-brushes", "فرش تنظيف", "ايكيا", "cleaning", 65, "طقم فرش تنظيف"),
      n("br-c-toilet-brush", "فرش حمام", "ايكيا", "bathroom", 55, "فرشاة تواليت"),
      n("br-c-floor-brush", "فرش أرضيات", "ايكيا", "cleaning", 90, "فرشاة أرضيات"),
      n("br-c-detail-brush", "فرشة صغيرة", "ايكيا", "cleaning", 35, "فرشة زوايا"),
      n("br-c-duster", "منفضة", "ايكيا", "cleaning", 40, "منفضة غبار"),
      n("br-c-electric-duster", "منفضة كهربائية", "شاومي", "cleaning", 890, "منفضة شحن"),
      n("br-c-spray-bottles-set", "بخاخات تنظيف", "ايكيا", "cleaning", 70, "طقم بخاخات"),
      n("br-c-spray-empty", "زجاجات رش", "ايكيا", "cleaning", 45, "زجاجات رش فارغة"),
      n("br-c-gloves", "جوانتي تنظيف", "كارفور", "cleaning", 25, "جوانتي مطاط"),
      n("br-c-microfiber", "فوط مايكروفايبر", "ايكيا", "cleaning", 90, "طقم مايكروفايبر"),
      n("br-c-floor-cloth", "فوط أرضيات", "ايكيا", "cleaning", 60, "فوط أرضيات"),
      n("br-c-kitchen-cloth", "فوط مطبخ", "ايكيا", "cleaning", 50, "فوط تنشيف مطبخ"),
      n("br-c-sponges", "إسفنج تنظيف", "كارفور", "cleaning", 28, "إسفنج متعدد"),
      n("br-c-laundry-basket", "سلة غسيل", "ايكيا", "cleaning", 160, "سلة غسيل قماش"),
      n("br-c-trash", "سلة قمامة", "ايكيا", "cleaning", 140, "سلة قمامة عامة"),
      n("br-c-caddy", "منظم أدوات التنظيف", "ايكيا", "storage", 120, "حامل منظفات"),
      n("br-c-mop-holder", "حامل الممسحة", "ايكيا", "storage", 80, "حامل ممسحة ومقشة"),
      n("br-c-bags", "أكياس قمامة", "كارفور", "cleaning", 40, "أكياس قمامة رول"),
      n("br-c-floor-cleaner", "منظفات أرضيات", "ديتول", "cleaning", 85, "منظف أرضيات"),
      n("br-c-glass-cleaner", "منظف زجاج", "فيتري", "cleaning", 55, "منظف زجاج"),
      n("br-c-kitchen-cleaner", "منظف مطبخ", "فيتري", "cleaning", 60, "مزيل دهون"),
      n("br-c-bath-cleaner", "منظف حمام", "هاريك", "cleaning", 58, "منظف حمام"),
      n("br-c-disinfectant", "مطهر", "ديتول", "cleaning", 75, "مطهر أسطح"),
      n("br-c-floor-scent", "معطر أرضيات", "كارفور", "cleaning", 50, "معطر أرضيات"),
      n("br-c-air-fresh", "معطر جو", "أير ويك", "cleaning", 65, "معطر جو"),
    ],
  },
  {
    id: "bathroom",
    title: "الحمام",
    commercial: "Bathroom",
    blurb: "ستارة ودواسة وفوط ومنظمات: الحمام يبان جاهز من يوم الاستلام.",
    items: [
      n("br-b-curtain", "ستارة حمام", "ايكيا", "bathroom", 180, "ستارة حمام مقاومة للماء"),
      n("br-b-mat", "دواسة حمام", "ايكيا", "bathroom", 120, "دواسة ماصة"),
      n("br-b-set", "طقم حمام", "ايكيا", "bathroom", 260, "طقم إكسسوار حمام"),
      n("br-b-soap-dish", "حامل صابون", "ايكيا", "bathroom", 45, "حامل صابون"),
      n("br-b-shampoo-caddy", "حامل شامبو", "ايكيا", "bathroom", 90, "رف شامبو للبانيو"),
      n("br-b-brush-holder", "حامل فرش أسنان", "ايكيا", "bathroom", 55, "حامل فرش"),
      n("br-b-rinse-cup", "كوب مضمضة", "ايكيا", "bathroom", 30, "كوب مضمضة"),
      n("br-b-bin", "سلة حمام", "ايكيا", "bathroom", 85, "سلة حمام صغيرة"),
      n("br-b-toilet-brush", "فرشاة حمام", "ايكيا", "bathroom", 50, "فرشاة تواليت بغطاء"),
      n("br-b-tissue-stand", "حامل مناديل", "ايكيا", "bathroom", 70, "حامل مناديل تواليت"),
      n("br-b-tp", "مناديل تواليت", "فاين", "bathroom", 95, "كرتون مناديل تواليت"),
      n("br-b-organizer", "منظم حمام", "ايكيا", "storage", 160, "منظم حمام للركن"),
      n("br-b-cosmetics-org", "منظم مستحضرات", "ايكيا", "storage", 140, "منظم كريمات"),
      n("br-b-hooks", "شماعات حمام", "ايكيا", "bathroom", 60, "شماعات فوط"),
      n("br-b-hand-towel", "فوطة يد", "ايكيا", "textiles", 70, "فوطة يد"),
      n("br-b-face-towel", "فوطة وجه", "ايكيا", "textiles", 55, "فوطة وجه"),
      n("br-b-hair-towel", "فوطة شعر", "ايكيا", "textiles", 80, "فوطة شعر ماصة"),
      ex("bath-towels-8", "فوطة حمام"),
      n("br-b-robe", "روب حمام", "كوتونيل", "textiles", 390, "روب حمام قطن"),
      n("br-b-slippers", "شبشب حمام", "ايكيا", "shoes", 75, "شبشب حمام ضد الانزلاق"),
      n("br-b-mirror", "مرآة", "ايكيا", "bathroom", 220, "مرآة حمام"),
      n("br-b-hamper", "سلة غسيل", "ايكيا", "bathroom", 170, "سلة غسيل للحمام"),
      n("br-b-refill-bottles", "زجاجات صابون وشامبو قابلة لإعادة التعبئة", "ايكيا", "bathroom", 110, "زجاجات إعادة تعبئة"),
    ],
  },
  {
    id: "bedroom",
    title: "غرفة النوم والمفروشات",
    commercial: "Bedroom",
    blurb: "ملايات ولحاف ومخدات ومنظمات الدولاب — مش بس السرير.",
    items: [
      n("br-bed-sheets", "ملايات سرير", "هومزمارت", "textiles", 420, "ملايات قطن كينج"),
      n("br-bed-fitted", "ملايات استك", "هومزمارت", "textiles", 280, "ملاءة استك"),
      n("br-bed-sheet-set", "أطقم ملايات", "هومزمارت", "textiles", 690, "طقم ملايات 4 قطع"),
      n("br-bed-duvet-cover", "كفرات لحاف", "هومزمارت", "textiles", 380, "كفر لحاف"),
      ex("cotton-duvet", "لحاف"),
      n("br-bed-blankets", "بطاطين", "هومزمارت", "textiles", 450, "بطانية ثقيلة"),
      n("br-bed-summer", "بطانية صيفي", "هومزمارت", "textiles", 290, "بطانية صيفي خفيفة"),
      n("br-bed-winter", "بطانية شتوي", "هومزمارت", "textiles", 520, "بطانية شتوي"),
      n("br-bed-coverlet", "مفرش سرير", "هومزمارت", "textiles", 340, "مفرش سرير"),
      n("br-bed-kuverta", "كوفرتة", "هومزمارت", "textiles", 410, "كوفرتة"),
      n("br-bed-kids-duvet", "لحاف أطفال مستقبلًا", "هومزمارت", "baby", 260, "لحاف أطفال"),
      n("br-bed-sleep-pillows", "مخدات نوم", "هومزمارت", "textiles", 240, "زوج مخدات نوم"),
      n("br-bed-decor-pillows", "مخدات ديكور", "هومزمارت", "decor", 180, "خدديات ديكور"),
      n("br-bed-mattress-prot", "واقي مرتبة", "هومزمارت", "textiles", 320, "واقي مرتبة ضد الماء"),
      n("br-bed-pillow-prot", "واقي مخدة", "هومزمارت", "textiles", 90, "واقي مخدة"),
      n("br-bed-extra-mattress", "مراتب إضافية", "هومزمارت", "textiles", 1890, "مرتبة ضيف"),
      n("br-bed-ortho", "مخدة طبية", "هومزمارت", "textiles", 280, "مخدة طبية"),
      n("br-bed-cushions", "خدديات", "هومزمارت", "decor", 160, "طقم خدديات"),
      n("br-bed-pillowcases", "كيس مخدة", "هومزمارت", "textiles", 80, "أطقم كيس مخدة"),
      n("br-bed-curtains", "ستائر", "هومزمارت", "decor", 690, "ستائر غرفة النوم"),
      n("br-bed-hangers", "شماعات ملابس", "ايكيا", "storage", 90, "شماعات خشب"),
      n("br-bed-closet-org", "منظمات دولاب", "ايكيا", "storage", 220, "منظم دولاب"),
      n("br-bed-int-org", "منظم ملابس داخلي", "ايكيا", "storage", 140, "منظم لانجري"),
      n("br-bed-shoe-org", "منظم أحذية", "ايكيا", "storage", 180, "منظم أحذية"),
      n("br-bed-storage-bags", "أكياس تخزين الملابس", "ايكيا", "storage", 70, "أكياس تخزين"),
      n("br-bed-vac-bags", "أكياس تفريغ هواء", "ايكيا", "storage", 95, "أكياس تفريغ"),
      n("br-bed-laundry", "سلة ملابس", "ايكيا", "storage", 150, "سلة ملابس للغرفة"),
    ],
  },
  {
    id: "wardrobe",
    title: "الملابس واللانجري",
    commercial: "Bridal Essentials",
    blurb: "بيت وخروج وبيجامة ومناسبات — مش جهاز كهربا بس.",
    items: [
      n("br-w-homewear", "ملابس بيت", "ديفاكتو", "women-wear", 320, "طقم بيت مريح"),
      ex("cotton-pajamas", "بيجامات"),
      n("br-w-training", "تريننجات", "ديفاكتو", "women-wear", 410, "تريننج خروج خفيف"),
      n("br-w-outing", "ملابس خروج", "نمشي", "women-wear", 690, "قطع خروج أساسية"),
      n("br-w-underwear", "ملابس داخلية", "كوتونيل", "women-wear", 280, "طقم داخلي قطن"),
      n("br-w-lingerie", "لانجري", "كوتونيل", "bridal-wear", 450, "طقم لانجري"),
      n("br-w-bras", "برا", "كوتونيل", "women-wear", 220, "برا يومي"),
      n("br-w-shorts", "شورتات", "كوتونيل", "women-wear", 140, "شورتات قطن"),
      n("br-w-robe", "روب", "كوتونيل", "pajamas", 360, "روب خفيف"),
      n("br-w-coverup", "كاش مايو", "نمشي", "women-wear", 290, "كاش مايو"),
      n("br-w-socks", "شرابات", "كوتونيل", "women-wear", 80, "شرابات قطن"),
      ex("bride-slippers", "شباشب"),
      n("br-w-shoes", "أحذية", "نمشي", "shoes", 790, "حذاء خروج"),
      ex("evening-bag", "شنط"),
      n("br-w-belt", "حزام", "نمشي", "accessories", 160, "حزام جلد"),
      ex("zircon-set", "إكسسوارات"),
      n("br-w-hijab", "طرح/إيشاربات", "كوتونيل", "accessories", 180, "طرح وإيشاربات"),
      ex("bridal-dress", "ملابس المناسبات"),
      n("br-w-honeymoon", "ملابس شهر العسل", "نمشي", "bridal-wear", 890, "قطع شهر العسل"),
    ],
  },
  {
    id: "beauty",
    title: "العناية الشخصية والتجميل",
    commercial: "Beauty",
    blurb: "من كريم الأساس لزيت الشعر: روتين العروسة كامل بمقارنة أسعار.",
    items: [
      n("br-m-kit", "ميكب", "لوريال", "beauty", 890, "طقم مكياج أساسي"),
      n("br-m-foundation", "كريم أساس", "مايبيلين", "beauty", 320, "كريم أساس"),
      n("br-m-concealer", "كونسيلر", "مايبيلين", "beauty", 210, "كونسيلر"),
      n("br-m-powder", "بودرة", "مايبيلين", "beauty", 190, "بودرة تثبيت"),
      n("br-m-blush", "بلاشر", "لوريال", "beauty", 180, "بلاشر"),
      n("br-m-highlighter", "هايلايتر", "لوريال", "beauty", 200, "هايلايتر"),
      n("br-m-liner", "آيلاينر", "مايبيلين", "beauty", 140, "آيلاينر"),
      n("br-m-mascara", "ماسكرا", "مايبيلين", "beauty", 170, "ماسكرا"),
      n("br-m-shadow", "آيشادو", "لوريال", "beauty", 240, "باليت آيشادو"),
      n("br-m-lipstick", "روج", "لوريال", "beauty", 160, "روج"),
      n("br-m-lip-liner", "محدد شفايف", "مايبيلين", "beauty", 95, "محدد شفايف"),
      n("br-m-setting", "مثبت ميكب", "لوريال", "beauty", 280, "مثبت مكياج"),
      n("br-m-remover", "مزيل ميكب", "نيفيا", "beauty", 110, "مزيل مكياج"),
      n("br-m-brushes", "فرش ميكب", "ريل تكنيك", "beauty", 260, "طقم فرش"),
      n("br-m-sponge", "إسفنجة ميكب", "بيوتي بلندر", "beauty", 90, "إسفنجة دمج"),
      n("br-m-organizer", "منظم ميكب", "ايكيا", "storage", 180, "منظم مكياج"),
      n("br-m-mirror", "مراية ميكب", "ايكيا", "beauty", 220, "مراية مكياج"),
      ex("lattafa-perfume", "عطور"),
      n("br-m-splash", "بودي سبلاش", "باتشي", "beauty", 180, "بودي سبلاش"),
      n("br-m-deodorant", "مزيل عرق", "نيفيا", "personal-care", 85, "مزيل عرق"),
      n("br-m-body-cream", "كريم جسم", "نيفيا", "personal-care", 95, "كريم جسم"),
      n("br-m-lotion", "لوشن", "نيفيا", "personal-care", 90, "لوشن"),
      n("br-m-body-oil", "زيت جسم", "نيفيا", "personal-care", 120, "زيت جسم"),
      n("br-m-cleanser", "غسول وجه", "سيفورا", "personal-care", 160, "غسول وجه"),
      n("br-m-toner", "تونر", "سيفورا", "personal-care", 140, "تونر"),
      n("br-m-serum", "سيروم", "سيفورا", "personal-care", 280, "سيروم وجه"),
      n("br-m-moisturizer", "مرطب", "نيفيا", "personal-care", 130, "مرطب وجه"),
      n("br-m-masks", "ماسكات", "سيفورا", "personal-care", 110, "ماسكات وجه"),
      n("br-m-spf", "واقي شمس", "لاروش", "personal-care", 320, "واقي شمس"),
      n("br-m-hair-range", "منتجات شعر", "لوريال", "personal-care", 240, "طقم عناية شعر"),
      n("br-m-shampoo", "شامبو", "لوريال", "personal-care", 95, "شامبو"),
      n("br-m-conditioner", "بلسم", "لوريال", "personal-care", 95, "بلسم"),
      n("br-m-hair-mask", "ماسك شعر", "لوريال", "personal-care", 140, "ماسك شعر"),
      n("br-m-hair-oil", "زيت شعر", "فاتيكا", "personal-care", 70, "زيت شعر"),
      n("br-m-hair-cream", "كريم شعر", "فاتيكا", "personal-care", 65, "كريم شعر"),
      n("br-m-hair-serum", "سيروم شعر", "لوريال", "personal-care", 150, "سيروم شعر"),
      ex("remington-dryer", "فرشاة شعر"),
      n("br-m-comb", "مشط", "ايكيا", "personal-care", 35, "مشط فك تشابك"),
      n("br-m-clip", "توكة", "ايكيا", "accessories", 40, "توك شعر"),
      n("br-m-elastics", "استك شعر", "ايكيا", "accessories", 25, "استك شعر"),
      n("br-m-bonnet", "بونيه", "كوتونيل", "accessories", 80, "بونيه ساتان"),
      n("br-m-manicure", "أدوات مانيكير", "ايكيا", "personal-care", 90, "طقم مانيكير"),
      n("br-m-pedicure", "أدوات باديكير", "ايكيا", "personal-care", 95, "طقم باديكير"),
      n("br-m-file", "مبرد أظافر", "ايكيا", "personal-care", 20, "مبرد أظافر"),
      n("br-m-clipper", "قصافة", "ايكيا", "personal-care", 25, "قصافة أظافر"),
      n("br-m-nail-remover", "مزيل طلاء أظافر", "كارفور", "personal-care", 30, "مزيل طلاء"),
    ],
  },
  {
    id: "laundry",
    title: "الغسيل والكي",
    commercial: "Laundry",
    blurb: "من الغسالة لمنعم الأقمشة ورول الوبر.",
    items: [
      ex("lg-washer-8", "غسالة"),
      n("br-l-airer", "منشر", "ايكيا", "accessories", 280, "منشر ملابس"),
      n("br-l-hangers", "شماعات", "ايكيا", "storage", 85, "شماعات غسيل"),
      n("br-l-pegs", "مشابك غسيل", "ايكيا", "accessories", 35, "مشابك غسيل"),
      n("br-l-basket", "سلة غسيل", "ايكيا", "storage", 150, "سلة غسيل كبيرة"),
      n("br-l-delicates", "أكياس غسيل للملابس الحساسة", "ايكيا", "accessories", 55, "أكياس غسيل رقيقة"),
      n("br-l-powder", "مسحوق غسيل", "أريال", "cleaning", 140, "مسحوق غسيل"),
      n("br-l-gel", "جل غسيل", "أريال", "cleaning", 160, "جل غسيل"),
      n("br-l-softener", "منعم أقمشة", "داوني", "cleaning", 95, "منعم أقمشة"),
      n("br-l-stain", "مزيل بقع", "فانيش", "cleaning", 85, "مزيل بقع"),
      n("br-l-bleach", "مبيض", "كلوركس", "cleaning", 50, "مبيض ملابس"),
      n("br-l-scent", "معطر ملابس", "داوني", "cleaning", 70, "معطر ملابس"),
      ex("tefal-iron", "مكواة"),
      n("br-l-steam-iron", "مكواة بخار", "فيليبس", "small-appliances", 1290, "مكواة بخار عمودية"),
      n("br-l-board", "ترابيزة كي", "ايكيا", "accessories", 490, "ترابيزة كي"),
      n("br-l-spray", "بخاخ مياه للكي", "ايكيا", "accessories", 40, "بخاخ كي"),
      n("br-l-lint", "رول إزالة الوبر", "ايكيا", "accessories", 35, "رول وبر"),
      n("br-l-clothes-brush", "فرشاة ملابس", "ايكيا", "accessories", 45, "فرشاة ملابس"),
    ],
  },
  {
    id: "electrical",
    title: "الأجهزة الكهربائية",
    commercial: "Electrical Accessories",
    blurb: "الأجهزة الكبيرة والصغيرة اللي بتتطلب ميزانية ومقارنة سعر جدية.",
    items: [
      ex("toshiba-fridge-16", "ثلاجة"),
      ex("lg-washer-8", "غسالة"),
      ex("unionaire-stove", "بوتاجاز"),
      n("br-e-oven", "فرن", "يونيفرسال", "small-appliances", 3290, "فرن كهربائي"),
      ex("toshiba-microwave", "ميكروويف"),
      ex("bosch-dishwasher", "غسالة أطباق"),
      n("br-e-hood", "شفاط", "فريش", "small-appliances", 2890, "شفاط مطبخ"),
      ex("sharp-ac-15", "تكييف"),
      ex("tornado-fan-18", "مروحة"),
      ex("fresh-heater", "سخان"),
      ex("kenwood-mixer", "خلاط"),
      n("br-e-chopper", "كبة", "براون", "small-appliances", 890, "كبة فرم"),
      n("br-e-food-proc", "محضر طعام", "كينوود", "small-appliances", 2490, "محضر طعام"),
      ex("braun-mixer", "هاند بلندر"),
      n("br-e-juicer", "عصارة", "كينوود", "small-appliances", 1690, "عصارة فواكه"),
      n("br-e-kneader", "عجان", "كينوود", "small-appliances", 4590, "عجان"),
      ex("philips-airfryer", "Air Fryer"),
      n("br-e-toaster", "توستر", "كينوود", "small-appliances", 690, "توستر"),
      n("br-e-sandwich", "ساندوتش ميكر", "كينوود", "small-appliances", 740, "ساندوتش ميكر"),
      n("br-e-coffee-machine", "ماكينة قهوة", "نسبريسو", "small-appliances", 3890, "ماكينة قهوة"),
      ex("kettle-kenwood", "غلاية"),
      n("br-e-hand-mixer", "مضرب كهربائي", "كينوود", "small-appliances", 890, "مضرب كهربائي"),
      ex("hoover-vacuum", "مكنسة كهربائية"),
      ex("robot-vacuum-tuya", "مكنسة روبوت"),
      ex("tefal-iron", "مكواة"),
    ],
  },
  {
    id: "electrical-bits",
    title: "الرفايع الكهربائية",
    commercial: "Electrical Accessories",
    blurb: "مشتركات وشواحن ولمبات: الحاجات اللي بتتقص أول أسبوع في الشقة.",
    items: [
      n("br-x-power-strip", "مشترك كهرباء", "ايكيا", "accessories", 120, "مشترك 4 فيش"),
      n("br-x-extension", "وصلات", "ايكيا", "accessories", 80, "وصلة كهرباء"),
      n("br-x-chargers", "شواحن", "أنكر", "accessories", 190, "شواحن متعددة"),
      n("br-x-cable-org", "منظمات أسلاك", "ايكيا", "storage", 70, "منظم كابلات"),
      n("br-x-bulbs", "لمبات", "فيليبس", "accessories", 90, "لمبات ليد"),
      n("br-x-lamp", "أباجورة", "ايكيا", "decor", 280, "أباجورة غرفة"),
      n("br-x-torch", "كشاف", "ايكيا", "accessories", 85, "كشاف يد"),
      n("br-x-night", "إضاءة ليلية", "ايكيا", "accessories", 60, "إضاءة ليلية"),
      n("br-x-emergency-light", "لمبات طوارئ", "فيليبس", "accessories", 140, "لمبة طوارئ شحن"),
      n("br-x-batteries", "بطاريات", "ديوراسيل", "accessories", 55, "بطاريات متنوعة"),
      n("br-x-powerbank", "باور بانك", "أنكر", "accessories", 490, "باور بانك"),
      n("br-x-wall-clock", "ساعة حائط", "ايكيا", "decor", 160, "ساعة حائط"),
      n("br-x-alarm", "منبه", "ايكيا", "accessories", 90, "منبه"),
      n("br-x-kitchen-scale", "ميزان مطبخ", "ايكيا", "kitchen-tools", 150, "ميزان مطبخ"),
      n("br-x-bath-scale", "ميزان حمام", "ايكيا", "bathroom", 280, "ميزان حمام"),
    ],
  },
  {
    id: "forgotten",
    title: "رفايع البيت اللي بتتنسي",
    commercial: "Emergency & Miscellaneous",
    blurb: "عدة ومسامير ولزق وخيط: الصندوق اللي بينقذ أول أسبوع.",
    items: [
      n("br-f-kit", "عدة صغيرة", "ايس", "accessories", 220, "طقم عدة صغير"),
      n("br-f-screwdrivers", "مفكات", "ايس", "accessories", 90, "طقم مفكات"),
      n("br-f-tape", "شطرطون", "ايس", "accessories", 25, "شريط لاصق عريض"),
      n("br-f-measure", "شريط قياس", "ايس", "accessories", 45, "متر قياس"),
      n("br-f-nails", "مسامير", "ايس", "accessories", 35, "علبة مسامير"),
      n("br-f-hooks", "خطافات حائط", "ايكيا", "accessories", 50, "خطافات حائط"),
      n("br-f-strong-tape", "لزق قوي", "ايس", "accessories", 40, "دبل فيس قوي"),
      n("br-f-plugs", "فيش كهرباء احتياطي", "ايس", "accessories", 30, "فيش احتياطي"),
      n("br-f-spare-bulbs", "لمبات احتياطي", "فيليبس", "accessories", 70, "لمبات احتياطي"),
      n("br-f-batteries", "بطاريات", "ديوراسيل", "accessories", 50, "بطاريات احتياطي"),
      n("br-f-lighter", "ولاعة", "كارفور", "accessories", 15, "ولاعة مطبخ"),
      n("br-f-scissors", "مقص", "ايكيا", "accessories", 35, "مقص متعدد"),
      n("br-f-cutter", "كاتر", "ايكيا", "accessories", 25, "كاتر"),
      n("br-f-needle", "خيط وإبرة", "ايكيا", "accessories", 20, "خيط وإبر"),
      n("br-f-sewing", "عدة خياطة", "ايكيا", "accessories", 55, "طقم خياطة"),
      n("br-f-pins", "سوستة/دبابيس أمان", "ايكيا", "accessories", 18, "دبابيس أمان"),
      n("br-f-flashlight", "كشاف", "ايكيا", "accessories", 80, "كشاف طوارئ"),
      n("br-f-step", "سلم صغير", "ايكيا", "accessories", 390, "سلم خطوتين"),
      n("br-f-toolbox", "صندوق أدوات", "ايس", "accessories", 180, "صندوق عدة"),
    ],
  },
  {
    id: "decor",
    title: "تنظيم وديكور البيت",
    commercial: "Home Decor",
    blurb: "براويز وسجاد وكوشنز: اللمسة اللي بتخلي الشقة بيت.",
    items: [
      n("br-d-frames", "براويز", "ايكيا", "decor", 160, "طقم براويز"),
      n("br-d-art", "تابلوهات", "هومزمارت", "decor", 390, "تابلوه حائط"),
      n("br-d-mirrors", "مرايات", "ايكيا", "decor", 420, "مراية ديكور"),
      n("br-d-vases", "فازات", "ايكيا", "decor", 140, "فازة"),
      n("br-d-plants", "نباتات صناعية", "ايكيا", "decor", 120, "نبات صناعي"),
      n("br-d-candles", "شموع", "ايكيا", "decor", 80, "شموع معطرة"),
      n("br-d-candlestick", "شمعدان", "ايكيا", "decor", 110, "شمعدان"),
      n("br-d-figurines", "تحف", "هومزمارت", "decor", 180, "تحفة صغيرة"),
      n("br-d-clocks", "ساعات حائط", "ايكيا", "decor", 170, "ساعة حائط ديكور"),
      n("br-d-rug", "سجاد", "هومزمارت", "decor", 1290, "سجاد صالة"),
      n("br-d-doormats", "دواسات", "ايكيا", "decor", 90, "دواسة باب"),
      n("br-d-curtains", "ستائر", "هومزمارت", "decor", 740, "ستائر صالة"),
      n("br-d-cushions", "كوشنز", "هومزمارت", "decor", 220, "طقم كوشنز"),
      n("br-d-sofa-cover", "أغطية أنتريه", "هومزمارت", "textiles", 390, "غطاء أنتريه"),
      n("br-d-table-cloth", "مفرش ترابيزة", "ايكيا", "textiles", 160, "مفرش ترابيزة"),
      n("br-d-organizers", "منظمات", "ايكيا", "storage", 150, "منظمات ديكور"),
      n("br-d-boxes", "صناديق تخزين", "ايكيا", "storage", 180, "صناديق تخزين"),
      n("br-d-baskets", "سلال ديكور", "ايكيا", "decor", 140, "سلال قماش"),
      n("br-d-key-holder", "حامل مفاتيح", "ايكيا", "decor", 70, "حامل مفاتيح"),
      n("br-d-wall-hooks", "شماعات حائط", "ايكيا", "decor", 85, "شماعات حائط"),
      n("br-d-shoe-rack", "منظم أحذية", "ايكيا", "storage", 210, "رف أحذية مدخل"),
    ],
  },
  {
    id: "storage",
    title: "التخزين والتنظيم",
    commercial: "Home Organization",
    blurb: "منظمات لكل ركن: أدراج، دولاب، مكياج، شنط، وأحزمة.",
    items: [
      n("br-s-drawer", "منظمات الأدراج", "ايكيا", "storage", 130, "منظم أدراج"),
      n("br-s-closet", "منظمات الدولاب", "ايكيا", "storage", 210, "منظم دولاب"),
      n("br-s-clothes", "منظمات الملابس", "ايكيا", "storage", 160, "منظم ملابس"),
      n("br-s-shoes", "منظمات الأحذية", "ايكيا", "storage", 190, "منظم أحذية"),
      n("br-s-beauty", "منظمات مستحضرات التجميل", "ايكيا", "storage", 170, "منظم تجميل"),
      n("br-s-bath", "منظمات الحمام", "ايكيا", "storage", 150, "منظم حمام"),
      n("br-s-kitchen", "منظمات المطبخ", "ايكيا", "storage", 180, "منظم مطبخ"),
      n("br-s-boxes", "علب تخزين", "ايكيا", "storage", 140, "علب تخزين"),
      n("br-s-jars", "برطمانات", "ايكيا", "kitchen-tools", 120, "برطمانات تنظيم"),
      n("br-s-plastic-baskets", "سلال بلاستيك", "ايكيا", "storage", 90, "سلال بلاستيك"),
      n("br-s-fabric-baskets", "سلال قماش", "ايكيا", "storage", 110, "سلال قماش"),
      n("br-s-chests", "صناديق تخزين", "ايكيا", "storage", 200, "صناديق بغطاء"),
      n("br-s-vac", "Vacuum Bags", "ايكيا", "storage", 95, "أكياس تفريغ"),
      n("br-s-labels", "Labels / استيكرات تسمية", "ايكيا", "storage", 40, "ستيكرات تسمية"),
      n("br-s-bag-holder", "حامل شنط", "ايكيا", "storage", 130, "حامل شنط"),
      n("br-s-belt-holder", "حامل أحزمة", "ايكيا", "storage", 70, "حامل أحزمة"),
      n("br-s-acc-holder", "حامل إكسسوارات", "ايكيا", "storage", 95, "حامل إكسسوارات"),
    ],
  },
  {
    id: "coffee",
    title: "حاجات القهوة والشاي",
    commercial: "Gift Sets",
    blurb: "ركن الضيافة: فناجين وكنكة وبرطمانات ومنظم كبسولات.",
    items: [
      n("br-ct-coffee-set", "طقم قهوة", "لومينارك", "kitchen-tools", 340, "طقم قهوة"),
      n("br-ct-tea-set", "طقم شاي", "لومينارك", "kitchen-tools", 390, "طقم شاي"),
      n("br-ct-cups", "فناجين", "لومينارك", "kitchen-tools", 180, "فناجين"),
      n("br-ct-mugs", "مجات", "ايكيا", "kitchen-tools", 150, "مجات قهوة"),
      n("br-ct-kanaka", "كنكة", "إمبريال", "kitchen-tools", 170, "كنكة"),
      n("br-ct-kettle", "غلاية", "كينوود", "small-appliances", 690, "غلاية شاي"),
      n("br-ct-pot", "براد", "زازا", "kitchen-tools", 280, "براد"),
      n("br-ct-tray", "صينية", "ايكيا", "kitchen-tools", 160, "صينية ضيافة"),
      n("br-ct-spoons", "ملاعق صغيرة", "وينسلو", "kitchen-tools", 70, "ملاعق قهوة"),
      n("br-ct-coffee-jar", "برطمان قهوة", "ايكيا", "kitchen-tools", 55, "برطمان قهوة"),
      n("br-ct-sugar-jar", "برطمان سكر", "ايكيا", "kitchen-tools", 50, "برطمان سكر"),
      n("br-ct-tea-jar", "برطمان شاي", "ايكيا", "kitchen-tools", 50, "برطمان شاي"),
      n("br-ct-nescafe-jar", "برطمان نسكافيه", "ايكيا", "kitchen-tools", 50, "برطمان نسكافيه"),
      n("br-ct-station", "منظم قهوة", "ايكيا", "storage", 190, "ركن قهوة"),
      n("br-ct-capsules", "حامل كبسولات لو ماكينة قهوة", "ايكيا", "kitchen-tools", 120, "حامل كبسولات"),
    ],
  },
  {
    id: "travel",
    title: "شهر العسل والسفر",
    commercial: "Travel",
    blurb: "شنط ومنظمات وباسبور هولدر وعدة سفر صغيرة.",
    items: [
      n("br-tr-luggage", "شنط سفر", "أمريكان توريستر", "travel", 2490, "شنطة سفر متوسطة"),
      n("br-tr-handbag", "شنطة Hand Bag", "نمشي", "bags", 890, "شنطة يد للسفر"),
      n("br-tr-makeup-bag", "شنطة مكياج", "نمشي", "travel", 220, "شنطة مكياج سفر"),
      n("br-tr-bag-org", "منظم شنطة", "ايكيا", "travel", 90, "منظم شنطة"),
      n("br-tr-packing", "منظمات ملابس للسفر", "ايكيا", "travel", 160, "كيوبس سفر"),
      n("br-tr-passport", "باسبور هولدر", "نمشي", "travel", 120, "حافظة باسبور"),
      n("br-tr-bottles", "Travel Bottles", "ايكيا", "travel", 80, "زجاجات سفر"),
      n("br-tr-toothbrush", "فرشاة أسنان للسفر", "أورال بي", "travel", 45, "فرشاة سفر"),
      n("br-tr-slippers", "شبشب سفر", "ايكيا", "shoes", 70, "شبشب سفر قابل للطي"),
      n("br-tr-neck", "Neck Pillow", "ايكيا", "travel", 140, "مخدة رقبة"),
      n("br-tr-lock", "قفل شنطة", "ايس", "travel", 55, "قفل TSA"),
      n("br-tr-scale", "ميزان شنط", "ايكيا", "travel", 95, "ميزان شنط"),
      n("br-tr-multi-charger", "شاحن متعدد", "أنكر", "travel", 240, "شاحن سفر"),
      n("br-tr-powerbank", "باور بانك", "أنكر", "travel", 420, "باور بانك سفر"),
      n("br-tr-first-aid", "حقيبة إسعافات أولية", "سيف", "emergency", 160, "حقيبة إسعافات سفر"),
    ],
  },
  {
    id: "bridal",
    title: "رفايع خاصة بالعروسة والجواز",
    commercial: "Bridal Essentials",
    blurb: "لانجري وروب ومراية بإضاءة وبوكس ذكريات — مش للبيت بس للعروسة.",
    items: [
      n("br-br-lingerie", "لانجري شهر العسل", "كوتونيل", "bridal-wear", 520, "لانجري شهر العسل"),
      n("br-br-robe", "روب عروسة", "كوتونيل", "bridal-wear", 480, "روب عروسة"),
      n("br-br-slippers", "شبشب عروسة", "نمشي", "shoes", 190, "شبشب عروسة"),
      n("br-br-pj", "بيجاما عروسة", "كوتونيل", "pajamas", 390, "بيجاما عروسة"),
      n("br-br-care-kit", "طقم عناية شخصي", "نيفيا", "personal-care", 280, "طقم عناية"),
      n("br-br-perfume", "عطور", "لطافة", "beauty", 450, "عطر عروسة"),
      n("br-br-candles", "شموع", "ايكيا", "decor", 90, "شموع رومانسية"),
      n("br-br-oil", "مساج أويل", "نيفيا", "personal-care", 110, "زيت مساج"),
      n("br-br-lingerie-org", "منظمات للانجري", "ايكيا", "storage", 130, "منظم لانجري"),
      n("br-br-acc-org", "منظم إكسسوارات", "ايكيا", "storage", 120, "منظم إكسسوار"),
      n("br-br-jewelry-box", "Jewelry Box", "ايكيا", "jewelry", 260, "صندوق مجوهرات"),
      n("br-br-makeup-org", "منظم مكياج", "ايكيا", "storage", 190, "منظم مكياج عروسة"),
      n("br-br-light-mirror", "مراية بإضاءة", "ايكيا", "beauty", 490, "مراية مكياج مضيئة"),
      n("br-br-memory", "بوكس ذكريات", "ايكيا", "decor", 160, "صندوق ذكريات"),
      n("br-br-album", "ألبوم صور", "ايكيا", "decor", 140, "ألبوم صور"),
      n("br-br-gifts", "هدايا بسيطة للزوج", "نمشي", "accessories", 220, "هدية صغيرة للزوج"),
    ],
  },
  {
    id: "emergency",
    title: "بوكس الطوارئ",
    commercial: "Emergency & Miscellaneous",
    blurb: "ترمومتر وشاش وكمادات وعدة صغيرة: الصندوق اللي بيتفتح الساعة 2 بالليل.",
    items: [
      n("br-em-thermo", "ترمومتر", "أومرون", "emergency", 180, "ترمومتر"),
      n("br-em-alcohol", "كحول/مطهر", "سيف", "emergency", 40, "كحول طبي"),
      n("br-em-cotton", "قطن", "سيف", "emergency", 25, "قطن طبي"),
      n("br-em-gauze", "شاش", "سيف", "emergency", 30, "شاش معقم"),
      n("br-em-plaster", "بلاستر", "هانزابلاست", "emergency", 35, "بلاستر"),
      n("br-em-tape", "شريط طبي", "سيف", "emergency", 28, "شريط طبي"),
      n("br-em-scissors", "مقص صغير", "سيف", "emergency", 40, "مقص إسعاف"),
      n("br-em-gloves", "جوانتي", "سيف", "emergency", 30, "جوانتي طبي"),
      n("br-em-compress", "كمادات باردة/ساخنة", "سيف", "emergency", 70, "كمادات"),
      n("br-em-otc", "أدوية أساسية غير وصفية حسب الحاجة", "سيف", "emergency", 150, "بوكس مسكنات وخافض حرارة حسب الحاجة"),
      n("br-em-torch", "كشاف", "ايكيا", "emergency", 75, "كشاف طوارئ"),
      n("br-em-batteries", "بطاريات", "ديوراسيل", "emergency", 45, "بطاريات للطوارئ"),
      n("br-em-sewing", "عدة خياطة", "ايكيا", "emergency", 50, "عدة خياطة طوارئ"),
      n("br-em-tools", "عدة أدوات صغيرة", "ايس", "emergency", 160, "عدة صغيرة للطوارئ"),
    ],
  },
  {
    id: "baby",
    title: "حاجات مستقبلية ممكن تتجاب من البداية",
    commercial: "Gift Sets",
    blurb: "مش لازم دلوقتي — بس لو هتجهّزي الركن بدري، القايمة جاهزة.",
    items: [
      n("br-bb-sheets", "ملايات أطفال", "هومزمارت", "baby", 180, "ملايات أطفال"),
      n("br-bb-blankets", "بطاطين أطفال", "هومزمارت", "baby", 160, "بطانية أطفال"),
      n("br-bb-towels", "فوط أطفال", "ايكيا", "baby", 120, "فوط أطفال"),
      n("br-bb-org", "منظمات أطفال", "ايكيا", "baby", 140, "منظم أطفال"),
      n("br-bb-hangers", "شماعات أطفال", "ايكيا", "baby", 50, "شماعات أطفال"),
      n("br-bb-boxes", "صناديق تخزين", "ايكيا", "baby", 110, "صناديق أطفال"),
      n("br-bb-chair", "كرسي أطفال", "ايكيا", "baby", 890, "كرسي أطفال"),
      n("br-bb-toys", "ألعاب أطفال", "ايكيا", "baby", 220, "ألعاب أولية"),
      n("br-bb-feeding", "مستلزمات رضاعة", "فيليبس أفنت", "baby", 340, "طقم رضاعة"),
    ],
  },
];

export const brideProducts: Product[] = brideSections.flatMap((section) =>
  section.items
    .filter((item) => !item.existing)
    .map((item) =>
      makeSku(
        item.productId,
        item.name,
        item.brand ?? "وفّري هوم",
        item.category ?? "accessories",
        item.price ?? 99,
        item.hint ?? "بند جهاز عروسة",
      ),
    ),
);

export const brideItemCount = brideSections.reduce((n, s) => n + s.items.length, 0);

export const commercialBundles: {
  id: string;
  name: string;
  description: string;
  suggestedBudget: number;
  productIds: string[];
}[] = [
  {
    id: "box-kitchen",
    name: "بوكس رفايع المطبخ",
    description: "حلل وطاسات وسكاكين وعلب حفظ ومنظم درج",
    suggestedBudget: 8500,
    productIds: [
      "tefal-pots",
      "br-k-pans",
      "br-k-chef-knives",
      "br-k-food-boxes",
      "br-k-spice-set",
      "br-k-dish-rack",
      "kitchen-linens",
      "br-k-apron",
    ],
  },
  {
    id: "box-org",
    name: "بوكس تنظيم البيت",
    description: "منظمات أدراج ودولاب وصناديق وأكياس تفريغ",
    suggestedBudget: 2200,
    productIds: [
      "br-s-drawer",
      "br-s-closet",
      "br-s-shoes",
      "br-s-chests",
      "br-s-vac",
      "br-s-labels",
      "br-d-boxes",
    ],
  },
  {
    id: "box-bath",
    name: "بوكس الحمام",
    description: "ستارة ودواسة وفوط ومنظم وزجاجات إعادة تعبئة",
    suggestedBudget: 1800,
    productIds: [
      "br-b-curtain",
      "br-b-mat",
      "bath-towels-8",
      "br-b-set",
      "br-b-organizer",
      "br-b-refill-bottles",
      "br-b-robe",
    ],
  },
  {
    id: "box-bride-care",
    name: "بوكس العناية بالعروسة",
    description: "مكياج وعطر وروتين بشرة وشعر",
    suggestedBudget: 3500,
    productIds: [
      "br-m-kit",
      "lattafa-perfume",
      "br-m-brushes",
      "br-m-cleanser",
      "br-m-moisturizer",
      "br-m-spf",
      "br-m-shampoo",
      "remington-dryer",
    ],
  },
  {
    id: "box-honeymoon",
    name: "بوكس شهر العسل",
    description: "سفر ولانجري وروب وشنط صغيرة",
    suggestedBudget: 6200,
    productIds: [
      "br-tr-luggage",
      "br-br-lingerie",
      "br-br-robe",
      "br-w-honeymoon",
      "br-tr-passport",
      "br-tr-packing",
      "br-tr-powerbank",
    ],
  },
  {
    id: "box-first-home",
    name: "بوكس أول بيت",
    description: "مطبخ + تنظيف + حمام + رفايع كهربا الأساسية",
    suggestedBudget: 14000,
    productIds: [
      "tefal-pots",
      "br-t-dinner-set",
      "br-c-mop",
      "br-b-curtain",
      "br-x-power-strip",
      "br-f-kit",
      "kettle-kenwood",
      "tefal-iron",
    ],
  },
  {
    id: "box-cleaning",
    name: "بوكس التنظيف",
    description: "مقشة وممسحة ومنظفات وفوط مايكروفايبر",
    suggestedBudget: 1200,
    productIds: [
      "br-c-broom",
      "br-c-mop",
      "br-c-bucket",
      "br-c-microfiber",
      "br-c-floor-cleaner",
      "br-c-glass-cleaner",
      "br-c-disinfectant",
    ],
  },
  {
    id: "box-coffee",
    name: "بوكس القهوة والشاي",
    description: "طقم ضيافة وكنكة وبرطمانات وركن قهوة",
    suggestedBudget: 1600,
    productIds: [
      "br-ct-tea-set",
      "br-ct-coffee-set",
      "br-k-coffee-pot",
      "br-ct-station",
      "br-ct-sugar-jar",
      "br-t-tea-tray",
    ],
  },
  {
    id: "box-bits",
    name: "بوكس الرفايع كامل",
    description: "كهربا منسية + عدة + طوارئ",
    suggestedBudget: 1800,
    productIds: [
      "br-x-power-strip",
      "br-x-bulbs",
      "br-x-batteries",
      "br-f-kit",
      "br-f-toolbox",
      "br-em-thermo",
      "br-em-alcohol",
    ],
  },
  {
    id: "box-full",
    name: "العروسة Full Package",
    description: "شريحة من كل باب: مطبخ، حمام، مفروشات، عناية، سفر",
    suggestedBudget: 28000,
    productIds: [
      "tefal-pots",
      "br-t-dinner-set",
      "br-c-mop",
      "bath-towels-8",
      "cotton-duvet",
      "cotton-pajamas",
      "lattafa-perfume",
      "lg-washer-8",
      "br-tr-luggage",
      "br-br-robe",
      "br-s-closet",
      "br-em-thermo",
    ],
  },
];
