import type { Product } from "./types";

export const extraProducts: Product[] = [
  {
    id: "philips-airfryer",
    name: "قلاية هوائية فيليبس XXL 6.2 لتر",
    brand: "فيليبس",
    category: "small-appliances",
    barcode: "8710103891004",
    model: "HD9650",
    capacity: "6.2 لتر",
    highlights: ["من غير زيت تقريبًا", "سلتين", "تطبيق وصفات"],
    specs: [
      { label: "السعة", value: "6.2 لتر" },
      { label: "القدرة", value: "2225 وات" },
    ],
    listings: [
      {
        storeId: "jumia",
        price: 8990,
        rating: 4.6,
        reviews: 540,
        inStock: true,
        shipping: "غدًا",
        url: "https://www.jumia.com.eg/philips-airfryer",
        sku: "PH-AF-J",
        affiliateNetwork: "jumia",
        oldPrice: 10490,
      },
      {
        storeId: "carrefour",
        price: 8790,
        rating: 4.5,
        reviews: 80,
        inStock: true,
        shipping: "استلام هايبر",
        url: "https://www.carrefouregypt.com/philips-airfryer",
        sku: "PH-AF-CF",
        affiliateNetwork: "arabclicks",
      },
    ],
    reviewHighlights: [
      { author: "دينا م.", rating: 5, source: "جوميا", text: "البطاطس تقرمش من غير زيت كتير. بتنضف أسهل من الفرن." },
    ],
  },
  {
    id: "fresh-freezer-5",
    name: "ديب فريزر فريش 5 درج",
    brand: "فريش",
    category: "freezers",
    barcode: "6223003315050",
    model: "FDF-5D",
    capacity: "5 أدراج",
    highlights: ["صنع في مصر", "قفل أدراج", "توفير كهربا"],
    specs: [
      { label: "الأدراج", value: "5" },
      { label: "النوع", value: "رأسي" },
    ],
    listings: [
      {
        storeId: "raneen",
        price: 11290,
        rating: 4.2,
        reviews: 190,
        inStock: true,
        shipping: "توصيل أو فرع",
        url: "https://raneen.com/fresh-freezer",
        sku: "FR-FZ-RN",
        affiliateNetwork: "direct",
      },
      {
        storeId: "elaraby",
        price: 11800,
        rating: 4.3,
        reviews: 60,
        inStock: true,
        shipping: "وكيل",
        url: "https://www.elarabygroup.com/fresh-freezer",
        sku: "FR-FZ-AR",
        affiliateNetwork: "direct",
      },
    ],
    reviewHighlights: [
      { author: "سعاد أ.", rating: 4, source: "رنين", text: "بيمسك اللحمة للعيد. الدرج السفلي واسع." },
    ],
  },
  {
    id: "tornado-fan-18",
    name: "مروحة تورنيدو عمود 18 بوصة",
    brand: "تورنيدو",
    category: "fans",
    barcode: "6224012181809",
    model: "TWF-18",
    capacity: "18 بوصة",
    highlights: ["3 سرعات", "دوران يمين وشمال", "هادية نسبيًا"],
    specs: [
      { label: "المقاس", value: "18 بوصة" },
      { label: "التحكم", value: "ريموت" },
    ],
    listings: [
      {
        storeId: "jumia",
        price: 1890,
        rating: 4.3,
        reviews: 980,
        inStock: true,
        shipping: "توصيل سريع",
        url: "https://www.jumia.com.eg/tornado-fan",
        sku: "TOR-F-J",
        affiliateNetwork: "jumia",
      },
      {
        storeId: "raneen",
        price: 1750,
        rating: 4.1,
        reviews: 240,
        inStock: true,
        shipping: "فرع",
        url: "https://raneen.com/tornado-fan",
        sku: "TOR-F-RN",
        affiliateNetwork: "direct",
      },
    ],
    reviewHighlights: [
      { author: "يوسف ع.", rating: 4, source: "جوميا", text: "للهواء في الأوضة كفاية. الريموت عملي." },
    ],
  },
  {
    id: "samsung-soundbar",
    name: "ساوند بار سامسونج 3.1 قناة",
    brand: "Samsung",
    category: "audio",
    barcode: "8806094883101",
    model: "HW-B650",
    capacity: "3.1",
    highlights: ["سب ووفر لاسلكي", "HDMI ARC", "Dolby"],
    specs: [
      { label: "القنوات", value: "3.1" },
      { label: "القدرة", value: "430 وات" },
    ],
    listings: [
      {
        storeId: "twob",
        price: 12490,
        rating: 4.6,
        reviews: 70,
        inStock: true,
        shipping: "تركيب اختياري",
        url: "https://2b.com.eg/samsung-soundbar",
        sku: "SAM-SB-2B",
        affiliateNetwork: "arabclicks",
      },
      {
        storeId: "noon",
        price: 11990,
        rating: 4.5,
        reviews: 110,
        inStock: true,
        shipping: "غدًا",
        url: "https://www.noon.com/egypt-ar/samsung-soundbar",
        sku: "SAM-SB-N",
        affiliateNetwork: "noon",
      },
    ],
    reviewHighlights: [
      { author: "طارق ن.", rating: 5, source: "نون", text: "الصالون بقى سينما. الباس مش مزعج للجيران." },
    ],
  },
  {
    id: "water-dispenser-fresh",
    name: "مبرد مياه فريش 3 حنفيات",
    brand: "فريش",
    category: "water",
    barcode: "6223003313339",
    model: "FWD-3T",
    capacity: "3 حنفيات",
    highlights: ["ساخن وبارد وعادي", "خزان أطفال", "قفل أمان"],
    specs: [
      { label: "الحنفيات", value: "3" },
      { label: "النوع", value: "أرضي" },
    ],
    listings: [
      {
        storeId: "btech",
        price: 4290,
        rating: 4.2,
        reviews: 150,
        inStock: true,
        shipping: "توصيل",
        url: "https://btech.com/fresh-dispenser",
        sku: "FR-WD-B",
        affiliateNetwork: "arabclicks",
      },
      {
        storeId: "carrefour",
        price: 3990,
        rating: 4.0,
        reviews: 44,
        inStock: true,
        shipping: "هايبر",
        url: "https://www.carrefouregypt.com/fresh-dispenser",
        sku: "FR-WD-CF",
        affiliateNetwork: "arabclicks",
      },
    ],
    reviewHighlights: [
      { author: "هبة س.", rating: 4, source: "بي تك", text: "المي بتبرد في نص ساعة. الخزان سهل التنظيف." },
    ],
  },
  {
    id: "remington-dryer",
    name: "سشوار ريمنجتون 2200 وات",
    brand: "ريمنجتون",
    category: "personal-care",
    barcode: "5031320102209",
    model: "D5220",
    capacity: "2200 وات",
    highlights: ["أيوني", "2 فوهة", "حرارة قابلة للضبط"],
    specs: [
      { label: "القدرة", value: "2200 وات" },
      { label: "الكابل", value: "1.8 م" },
    ],
    listings: [
      {
        storeId: "amazon",
        price: 1290,
        rating: 4.4,
        reviews: 210,
        inStock: true,
        shipping: "أمازون",
        url: "https://www.amazon.eg/remington-dryer",
        sku: "REM-D-AZ",
        affiliateNetwork: "direct",
      },
      {
        storeId: "jumia",
        price: 1190,
        rating: 4.3,
        reviews: 640,
        inStock: true,
        shipping: "جوميا",
        url: "https://www.jumia.com.eg/remington-dryer",
        sku: "REM-D-J",
        affiliateNetwork: "jumia",
      },
    ],
    reviewHighlights: [
      { author: "لينا ح.", rating: 5, source: "أمازون", text: "بيجفف الشعر الطويل من غير ما يحرّق. خفيف في الإيد." },
    ],
  },
  {
    id: "robot-vacuum-tuya",
    name: "مكنسة روبوت بكاميرا ومسح",
    brand: "Xiaomi",
    category: "vacuums",
    barcode: "6934177700012",
    model: "S10+",
    capacity: "مسح + شفط",
    highlights: ["خريطة الشقة", "مسح مبلل", "تطبيق"],
    specs: [
      { label: "الشفط", value: "4000 باسكال" },
      { label: "البطارية", value: "5200 مللي" },
    ],
    listings: [
      {
        storeId: "noon",
        price: 8990,
        rating: 4.4,
        reviews: 320,
        inStock: true,
        shipping: "نون",
        url: "https://www.noon.com/egypt-ar/robot-vac",
        sku: "XI-RV-N",
        affiliateNetwork: "noon",
      },
      {
        storeId: "amazon",
        price: 9290,
        rating: 4.5,
        reviews: 90,
        inStock: true,
        shipping: "أمازون",
        url: "https://www.amazon.eg/robot-vac",
        sku: "XI-RV-AZ",
        affiliateNetwork: "direct",
      },
    ],
    reviewHighlights: [
      { author: "ماجد ف.", rating: 4, source: "نون", text: "بيعدّي تحت السرير. السجاد الثقيل بيحتاج تمريرة تانية." },
    ],
  },
  {
    id: "kettle-kenwood",
    name: "كتل كهربا كينوود 1.7 لتر",
    brand: "كينوود",
    category: "small-appliances",
    barcode: "5011423991708",
    model: "ZJP05",
    capacity: "1.7 لتر",
    highlights: ["فصل تلقائي", "فلتر كلس", "إضاءة"],
    specs: [
      { label: "السعة", value: "1.7 لتر" },
      { label: "القدرة", value: "2200 وات" },
    ],
    listings: [
      {
        storeId: "carrefour",
        price: 890,
        rating: 4.4,
        reviews: 55,
        inStock: true,
        shipping: "هايبر",
        url: "https://www.carrefouregypt.com/kenwood-kettle",
        sku: "KEN-K-CF",
        affiliateNetwork: "arabclicks",
      },
      {
        storeId: "jumia",
        price: 790,
        rating: 4.3,
        reviews: 410,
        inStock: true,
        shipping: "جوميا",
        url: "https://www.jumia.com.eg/kenwood-kettle",
        sku: "KEN-K-J",
        affiliateNetwork: "jumia",
      },
    ],
    reviewHighlights: [
      { author: "رشا ق.", rating: 5, source: "كارفور", text: "بيغلي في دقيقة. مناسب للشاي الصبح." },
    ],
  },
];
