import type { Store, StoreKind, VerticalId } from "./types";

const APPLIANCES: VerticalId[] = [
  "laundry",
  "cooling",
  "climate",
  "cooking",
  "cleaning",
  "water_heat",
  "av",
  "small_kitchen",
];
const HOME_BITS: VerticalId[] = [
  "small_kitchen",
  "accessories",
  "storage",
  "cleaning",
  "bathroom",
  "textiles",
];
const FASHION: VerticalId[] = [
  "fashion_women",
  "sleepwear",
  "shoes",
  "bags",
  "bridal",
  "accessories",
];
const BEAUTY: VerticalId[] = ["beauty", "personal_care"];
const FURN: VerticalId[] = ["furniture", "textiles", "decor", "storage"];

function add(
  id: string,
  name: string,
  kind: StoreKind,
  city: string,
  website: string,
  specialty: string,
  verticals: VerticalId[],
  skuEstimate: number,
): Store {
  return {
    id,
    name,
    kind,
    city,
    website,
    specialty,
    verticals,
    skuEstimate,
    connector: "partnership",
    status: "outreach",
    network: "direct",
    commissionNote: "تواصل تجاري / فيد لاحقًا — مش سكرابينج",
    affiliate: false,
  };
}

/** مصادر خريطة العروسة: أونلاين + أحياء. كلها outreach عشان متتوسّعش عروض الكتالوج. */
export const mapStores: Store[] = [
  add(
    "sednawy",
    "صيدناوي",
    "department",
    "فروع مصر",
    "https://www.sednawy.com",
    "وان ستوب: لبس + منزل + احتياجات متنوعة",
    [...FASHION, ...HOME_BITS, "furniture"],
    25000,
  ),
  add(
    "citystyle",
    "City Style",
    "department",
    "مولات",
    "https://www.citystyle-eg.com",
    "ديبارتمنت ستور: أزياء ومنزل",
    [...FASHION, ...HOME_BITS],
    12000,
  ),
  add(
    "cairosales",
    "أسواق القاهرة للمبيعات",
    "electronics",
    "القاهرة",
    "https://cairosales.com",
    "أجهزة كهربائية بأسعار جملة/تجزئة",
    APPLIANCES,
    4000,
  ),
  add(
    "gaballah",
    "جاب الله ستورز",
    "electronics",
    "القاهرة",
    "https://gaballahstores.com",
    "أجهزة منزلية وفروع مقارنة سعر",
    APPLIANCES,
    3500,
  ),
  add(
    "tawhid-nour",
    "التوحيد والنور",
    "department",
    "فروع مصر",
    "https://www.al-tawhid.com",
    "منزل ولبس وأدوات بأسعار شعبية",
    [...HOME_BITS, ...FASHION, "furniture"],
    30000,
  ),
  add(
    "zanussi-eg",
    "زانوسي مصر",
    "brand",
    "وكلاء",
    "https://www.zanussi.com.eg",
    "أجهزة بيضاء زانوسي",
    APPLIANCES,
    900,
  ),
  add(
    "abdelaziz",
    "شارع عبدالعزيز",
    "district",
    "وسط البلد — القاهرة",
    "https://maps.google.com/?q=Abdelaziz+Street+Cairo",
    "مقارنة أسعار أجهزة ورفايع وتلفونات على الطبيعة",
    [...APPLIANCES, "accessories"],
    50000,
  ),
  add(
    "nozha",
    "شارع النزهة",
    "district",
    "مصر الجديدة / النزهة",
    "https://maps.google.com/?q=El+Nozha+Street+Cairo",
    "رفايع وأدوات منزل ومفروشات",
    HOME_BITS,
    20000,
  ),
  add(
    "ataba",
    "العتبة",
    "district",
    "وسط القاهرة",
    "https://maps.google.com/?q=Ataba+Cairo",
    "أجهزة ورفايع ومفروشات جملة",
    [...APPLIANCES, ...HOME_BITS, "textiles"],
    40000,
  ),
  add(
    "hammam-tlat",
    "حمام التلات",
    "district",
    "الجمالية — القاهرة",
    "https://maps.google.com/?q=Hammam+El+Talat+Cairo",
    "منجم المطبخ: حلل، طاسات، صواني، تقديم، رفايع",
    ["small_kitchen", "accessories", "storage"],
    35000,
  ),
  add(
    "darb-saada",
    "درب سعادة",
    "district",
    "القاهرة الفاطمية",
    "https://maps.google.com/?q=Darb+Saada+Cairo",
    "أدوات منزل ورفايع رخيصة ومتنوعة",
    HOME_BITS,
    15000,
  ),
  add(
    "shubra",
    "شارع شبرا",
    "district",
    "شبرا — القاهرة",
    "https://maps.google.com/?q=Shubra+Street+Cairo",
    "رفايع وأدوات منزل ومفروشات",
    [...HOME_BITS, "textiles"],
    18000,
  ),
  add(
    "moski",
    "الموسكي",
    "district",
    "القاهرة",
    "https://maps.google.com/?q=Al+Moski+Cairo",
    "جملة أدوات منزل وإكسسوار",
    [...HOME_BITS, "accessories"],
    22000,
  ),
  add(
    "bab-shareya",
    "باب الشعرية",
    "district",
    "القاهرة",
    "https://maps.google.com/?q=Bab+El+Shaeria+Cairo",
    "أدوات منزل ورفايع",
    HOME_BITS,
    12000,
  ),
  add(
    "fagala",
    "الفجالة",
    "district",
    "القاهرة",
    "https://maps.google.com/?q=Faggala+Cairo",
    "أدوات مكتبية ومنزل وأحياء تجارية مجاورة",
    ["accessories", "storage"],
    8000,
  ),
  add(
    "azhar-housewares",
    "محلات الأزهر للأدوات المنزلية",
    "district",
    "الأزهر — القاهرة",
    "https://maps.google.com/?q=Al+Azhar+housewares+Cairo",
    "أدوات منزل وتقديم",
    HOME_BITS,
    10000,
  ),
  add(
    "sogha",
    "الصاغة ومحلات الذهب",
    "jewelry",
    "الموسكي / الصاغة",
    "https://maps.google.com/?q=Gold+souk+Cairo",
    "شبكات ودبل ومهر حسب السعر العالمي + المصنعية",
    ["jewelry"],
    8000,
  ),
  add(
    "mobica",
    "موبيكا",
    "furniture",
    "فروع مصر",
    "https://www.mobica.com",
    "أثاث ومفروشات محلية",
    FURN,
    4000,
  ),
  add(
    "ashley",
    "Ashley",
    "furniture",
    "مولات",
    "https://www.ashleyfurniture.com",
    "أثاث أمريكي في مصر",
    ["furniture", "decor"],
    2500,
  ),
  add(
    "townteam",
    "تاون تيم",
    "fashion",
    "فروع",
    "https://www.townteam.com",
    "لبس رجالي ومنزلي ومفروشات خفيفة",
    ["fashion_men", "sleepwear", "textiles"],
    6000,
  ),
  add(
    "lacasa",
    "لا كاسا",
    "furniture",
    "مصر",
    "https://www.lacasa-egypt.com",
    "مفروشات وأثاث منزلي",
    FURN,
    3000,
  ),
  add(
    "hm-home",
    "H&M Home",
    "furniture",
    "مولات H&M",
    "https://www2.hm.com/en_eg/home.html",
    "مفروشات وديكور خفيف",
    ["textiles", "decor", "storage"],
    4000,
  ),
  add(
    "thehome",
    "The Home",
    "furniture",
    "مولات",
    "https://www.thehome.com.eg",
    "أثاث وإكسسوار منزل",
    FURN,
    3500,
  ),
  add(
    "potterybarn",
    "Pottery Barn",
    "furniture",
    "مولات مختارة",
    "https://www.potterybarn.com",
    "أثاث وديكور أعلى فئة",
    FURN,
    2000,
  ),
  add(
    "cityfurniture",
    "City Furniture",
    "furniture",
    "مولات",
    "https://www.cityfurniture.com",
    "أثاث غرف وصالون",
    ["furniture", "decor"],
    2200,
  ),
  add(
    "damietta",
    "مدينة الأثاث بدمياط",
    "district",
    "دمياط",
    "https://maps.google.com/?q=Damietta+furniture+city",
    "أثاث محلي بأسعار المصنع",
    ["furniture", "textiles"],
    20000,
  ),
  add(
    "zara",
    "Zara",
    "fashion",
    "مولات",
    "https://www.zara.com/eg",
    "لبس خروج ومناسبات",
    FASHION,
    10000,
  ),
  add(
    "mango",
    "Mango",
    "fashion",
    "مولات",
    "https://shop.mango.com/eg",
    "لبس خروج",
    FASHION,
    8000,
  ),
  add(
    "randb",
    "R&B",
    "fashion",
    "فروع",
    "https://www.rnb.com.eg",
    "لبس يومي وبيت",
    ["fashion_women", "sleepwear"],
    5000,
  ),
  add(
    "concrete",
    "Concrete",
    "fashion",
    "مصر",
    "https://www.concrete.com.eg",
    "لبس حريمي محلي",
    ["fashion_women"],
    4000,
  ),
  add(
    "mobaco",
    "موباكو",
    "fashion",
    "فروع",
    "https://www.mobaco.com",
    "قطن مصري ولبس أساسي",
    ["fashion_women", "fashion_men", "sleepwear"],
    3500,
  ),
  add(
    "dalydress",
    "Dalydress",
    "fashion",
    "أونلاين + فروع",
    "https://dalydress.com",
    "ملابس بيت وعبايات",
    ["fashion_women", "sleepwear"],
    4500,
  ),
  add(
    "nayomi",
    "Nayomi",
    "fashion",
    "مولات",
    "https://www.nayomi.com",
    "لانجري وملابس نوم",
    ["bridal", "sleepwear"],
    3000,
  ),
  add(
    "lasenza",
    "La Senza",
    "fashion",
    "مولات",
    "https://www.lasenza.com",
    "لانجري",
    ["bridal", "sleepwear"],
    2500,
  ),
  add(
    "triumph",
    "Triumph",
    "fashion",
    "مولات",
    "https://www.triumph.com",
    "لانجري وملابس داخلية",
    ["sleepwear", "fashion_women"],
    2800,
  ),
  add(
    "ig-lingerie",
    "محلات لانجري على إنستجرام",
    "local",
    "أونلاين محلي",
    "https://www.instagram.com",
    "بوتيكات محلية — الربط لاحقًا بفيد التاجر",
    ["bridal", "sleepwear"],
    15000,
  ),
  add(
    "bata",
    "Bata",
    "fashion",
    "فروع",
    "https://www.bata.com.eg",
    "أحذية يومية",
    ["shoes"],
    4000,
  ),
  add(
    "aldo",
    "Aldo",
    "fashion",
    "مولات",
    "https://www.aldoshoes.com",
    "أحذية وشنط",
    ["shoes", "bags"],
    3500,
  ),
  add(
    "ck",
    "Charles & Keith",
    "fashion",
    "مولات",
    "https://www.charleskeith.com",
    "أحذية وشنط مناسبات",
    ["shoes", "bags"],
    3000,
  ),
  add(
    "shoemart",
    "Shoemart",
    "fashion",
    "مولات",
    "https://www.shoemart.com",
    "أحذية متنوعة",
    ["shoes"],
    4000,
  ),
  add(
    "ninewest",
    "Nine West",
    "fashion",
    "مولات",
    "https://www.ninewest.com",
    "أحذية وشنط",
    ["shoes", "bags"],
    2200,
  ),
  add(
    "leather-local",
    "محلات الجلد المحلية",
    "local",
    "القاهرة / الإسكندرية",
    "https://maps.google.com/?q=leather+bags+Cairo",
    "شنط وحزام جلد محلي",
    ["bags", "accessories"],
    5000,
  ),
  add(
    "vero-bridal",
    "Vero Bridal",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/verobridal",
    "فساتين فرح",
    ["bridal"],
    400,
  ),
  add(
    "mariage",
    "Mariage Wedding Dress",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/mariageegypt",
    "فساتين زفاف",
    ["bridal"],
    350,
  ),
  add(
    "lanovia",
    "La Novia Bridal Shop",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/lanovia",
    "فساتين عرايس",
    ["bridal"],
    300,
  ),
  add(
    "moller",
    "Moller Wedding Dresses",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/mollerwedding",
    "فساتين فرح",
    ["bridal"],
    280,
  ),
  add(
    "vogue-bridal",
    "Vogue Bridal Boutique",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/voguebridal",
    "بوتيك فساتين",
    ["bridal"],
    250,
  ),
  add(
    "glamour-dalia",
    "Glamour Bridal by Dalia Safwat",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/glamourbridal",
    "فساتين عرايس",
    ["bridal"],
    220,
  ),
  add(
    "chantelle",
    "Chantelle Wedding Dresses",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/chantellebridal",
    "فساتين فرح",
    ["bridal"],
    200,
  ),
  add(
    "whiteveil",
    "White Veil",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/whiteveil",
    "فساتين وطرح فرح",
    ["bridal", "accessories"],
    180,
  ),
  add(
    "malton",
    "Malton Bridal",
    "bridal",
    "القاهرة",
    "https://www.instagram.com/explore/tags/maltonbridal",
    "فساتين زفاف",
    ["bridal"],
    200,
  ),
  add(
    "swarovski",
    "Swarovski",
    "jewelry",
    "مولات",
    "https://www.swarovski.com",
    "كريستال وإكسسوار",
    ["jewelry", "accessories"],
    2000,
  ),
  add(
    "pandora",
    "Pandora",
    "jewelry",
    "مولات",
    "https://www.pandora.net",
    "إكسسوار تشارمز",
    ["jewelry"],
    1800,
  ),
  add(
    "damas",
    "Damas",
    "jewelry",
    "مولات",
    "https://www.damasjewellery.com",
    "ذهب ومجوهرات",
    ["jewelry"],
    2500,
  ),
  add(
    "azzafahmy",
    "عزة فهمي",
    "jewelry",
    "مصر",
    "https://www.azzafahmy.com",
    "مجوهرات مصرية فاخرة",
    ["jewelry"],
    800,
  ),
  add(
    "sephora",
    "Sephora",
    "beauty_retail",
    "مولات",
    "https://www.sephora.com",
    "مكياج وعناية عالمي",
    BEAUTY,
    8000,
  ),
  add(
    "faces",
    "Faces",
    "beauty_retail",
    "مولات",
    "https://www.faces.com",
    "تجميل وعطور",
    BEAUTY,
    6000,
  ),
  add(
    "mazaya",
    "مزايا",
    "beauty_retail",
    "فروع مصر",
    "https://www.mazaya-eg.com",
    "تجميل وعناية محلية",
    BEAUTY,
    5000,
  ),
  add(
    "eva",
    "إيفا كوزمتكس",
    "beauty_retail",
    "مصر",
    "https://www.eva-cosmetics.com",
    "عناية ومكياج مصري",
    BEAUTY,
    3000,
  ),
  add(
    "orchidia",
    "أوركيديا",
    "beauty_retail",
    "مصر",
    "https://www.orchidia.com",
    "عناية شخصية مصرية",
    BEAUTY,
    2500,
  ),
  add(
    "elezaby",
    "العزبي",
    "beauty_retail",
    "فروع",
    "https://www.elezabypharmacy.com",
    "صيدلية: عناية، مكياج خفيف، إسعاف",
    [...BEAUTY, "emergency"],
    12000,
  ),
  add(
    "p19011",
    "19011",
    "beauty_retail",
    "توصيل صيدليات",
    "https://www.19011.com",
    "تطبيق صيدليات وعناية",
    [...BEAUTY, "emergency"],
    9000,
  ),
  add(
    "beautymarket",
    "Beauty Market",
    "beauty_retail",
    "مصر",
    "https://www.beautymarket-eg.com",
    "تجميل بالجملة والتجزئة",
    BEAUTY,
    4000,
  ),
  add(
    "miniso",
    "Miniso",
    "department",
    "مولات",
    "https://www.miniso.com",
    "تنظيم، ديكور خفيف، هدايا، رفايع",
    ["storage", "decor", "accessories", "travel"],
    8000,
  ),
  add(
    "amtourister",
    "American Tourister",
    "fashion",
    "مولات + أونلاين",
    "https://www.americantourister.com",
    "شنط سفر",
    ["travel", "bags"],
    1500,
  ),
  add(
    "samsonite",
    "Samsonite",
    "fashion",
    "مولات",
    "https://www.samsonite.com",
    "شنط سفر",
    ["travel", "bags"],
    1400,
  ),
  add(
    "giftshops",
    "محلات الهدايا والورود",
    "local",
    "كل المدن",
    "https://maps.google.com/?q=gift+shop+Cairo",
    "هدايا خطوبة، شوكولاتة، ورد",
    ["accessories", "decor"],
    6000,
  ),
];
