import { arabicIncludes } from "./ar-fold";

export type NeedPri = "must" | "should" | "nice";

export type NeedItem = {
  name: string;
  source: string;
  pri: NeedPri;
};

export type NeedGroup = {
  id: string;
  phase: string;
  title: string;
  blurb: string;
  items: NeedItem[];
};

function i(name: string, source: string, pri: NeedPri = "must"): NeedItem {
  return { name, source, pri };
}

/** قاعدة احتياجات العروسة — بنود للتخطيط، مش كتالوج أسعار لكل سطر. */
export const needGroups: NeedGroup[] = [
  {
    id: "engagement",
    phase: "قبل الجواز",
    title: "الخطوبة",
    blurb: "ذهب ولبس وهدايا وتوزيعات قبل الفرح.",
    items: [
      i("دبلة", "gold"),
      i("شبكة", "gold"),
      i("ساعات", "fashion", "should"),
      i("شنط", "fashion"),
      i("أحذية", "fashion"),
      i("فساتين خروج", "fashion"),
      i("عبايات", "fashion"),
      i("لانجري", "lingerie"),
      i("بيجامات", "lingerie"),
      i("عطور", "beauty"),
      i("مكياج", "beauty"),
      i("عناية بشرة", "beauty"),
      i("عناية شعر", "beauty"),
      i("مانيكير", "beauty", "should"),
      i("بوكس خطوبة", "gifts"),
      i("توزيعات", "gifts"),
      i("دعوات", "gifts", "should"),
      i("ديكور حفلة الخطوبة", "services", "nice"),
      i("مستلزمات تصوير", "gifts", "should"),
    ],
  },
  {
    id: "wedding-day",
    phase: "يوم الفرح",
    title: "تجهيزات الفرح",
    blurb: "فستان وإكسسوار وميكب — وللعريس بدلة.",
    items: [
      i("فستان الزفاف", "bridal"),
      i("طرحة", "bridal"),
      i("تاج", "bridal", "should"),
      i("حذاء العروسة", "fashion"),
      i("كلتش", "fashion"),
      i("إكسسوار شعر", "bridal", "should"),
      i("روب العروسة", "lingerie"),
      i("شبشب", "fashion"),
      i("رموش وعدسات", "beauty", "should"),
      i("أدوات شعر", "beauty"),
      i("بدلة العريس", "fashion"),
      i("قميص وكرافتة", "fashion"),
      i("حذاء العريس", "fashion"),
      i("أزرار كم", "fashion", "nice"),
    ],
  },
  {
    id: "memories",
    phase: "يوم الفرح",
    title: "التصوير والذكريات",
    blurb: "خدمة مصور + منتجات ذكرى.",
    items: [
      i("مصور / فيديو", "services"),
      i("ألبوم فرح", "gifts", "should"),
      i("براويز", "decor"),
      i("دفتر مدعوين", "gifts", "nice"),
      i("كاميرا فورية", "gifts", "nice"),
      i("صندوق ذكريات", "gifts", "should"),
      i("إطار عقد الزواج", "gifts", "should"),
      i("هدايا باسمين", "gifts", "nice"),
      i("لافتة / نيون", "services", "nice"),
    ],
  },
  {
    id: "beauty-box",
    phase: "تجميل",
    title: "بوكس العناية",
    blurb: "روتين البشرة والجسم والشعر قبل الفرح.",
    items: [
      i("غسول وتونر", "beauty"),
      i("سيروم ومرطب", "beauty"),
      i("واقي شمس", "beauty"),
      i("لوشن وسكراب", "beauty"),
      i("جل استحمام", "grocery"),
      i("مزيل عرق", "beauty"),
      i("عطر", "beauty"),
      i("شامبو وبلسم", "beauty"),
      i("ماسك وزيت شعر", "beauty"),
      i("سشوار", "appliances"),
      i("مكواة فرد / تجعيد", "appliances", "should"),
      i("ماكينة تشذيب", "beauty", "should"),
      i("شمع إزالة", "beauty", "should"),
    ],
  },
  {
    id: "nail-tools",
    phase: "تجميل",
    title: "أدوات منيكر وميكب",
    blurb: "رفايع التجميل اللي بترفع متوسط السلة.",
    items: [
      i("قصافة ومبرد", "beauty"),
      i("طلاء ومزيل", "beauty"),
      i("لمبة UV", "beauty", "nice"),
      i("ملقاط وكيرلر", "beauty"),
      i("مراية مكياج", "beauty"),
      i("فرش وبيوتي بلندر", "beauty"),
      i("منظم مكياج", "storage"),
      i("قطن وأعواد", "grocery"),
      i("رولر ثلج / جواشا", "beauty", "nice"),
    ],
  },
  {
    id: "wardrobe",
    phase: "لبس",
    title: "دولاب العروسة",
    blurb: "خروج، بيت، داخلي، إكسسوار.",
    items: [
      i("فساتين وبلوزات", "fashion"),
      i("جينز وبناطيل", "fashion"),
      i("جاكيت ومعطف", "fashion", "should"),
      i("عبايات وطرح", "fashion"),
      i("بيجامات وروبات", "lingerie"),
      i("شباشب بيت", "fashion"),
      i("حمالات وداخلي", "lingerie"),
      i("شرابات وشيبوير", "lingerie", "should"),
      i("شنط وأحذية", "fashion"),
      i("حزام ومحفظة", "fashion", "should"),
      i("نظارة وساعة", "fashion", "nice"),
      i("إكسسوار شعر", "fashion", "should"),
    ],
  },
  {
    id: "honeymoon",
    phase: "شهر العسل",
    title: "سفر وشهر العسل",
    blurb: "لبس بحر + عدة السفر مش شنطة وبس.",
    items: [
      i("ملابس بحر", "fashion"),
      i("فساتين سفر", "fashion"),
      i("شنطة كبيرة وكابينة", "travel"),
      i("حامل باسبور ومحفظة سفر", "travel"),
      i("مكعبات تغليف", "travel"),
      i("شنطة أدوات شخصية", "travel"),
      i("زجاجات سفر", "travel"),
      i("وسادة رقبة وغطاء عين", "travel", "should"),
      i("قفل وميزان شنط", "travel", "should"),
      i("محول كهربا وباور بانك", "travel"),
      i("كاميرا سفر", "travel", "nice"),
      i("شنطة بحر وفوطة", "travel"),
      i("نظارة وقبعة وحذاء سفر", "fashion"),
      i("لبس زوجين لشهر العسل", "fashion", "should"),
      i("تأمين سفر", "services", "should"),
      i("فندق / باكدج شهر عسل", "services"),
      i("طيران ونقل المطار", "services", "should"),
      i("جولات سياحية", "services", "nice"),
    ],
  },
  {
    id: "first-week",
    phase: "أول بيت",
    title: "بوكس أول أسبوع",
    blurb: "تطبخي وتنضفي من غير مشوار يومي.",
    items: [
      i("أطباق وكوبايات ومعالق", "kitchen"),
      i("طاسات وحلل وسكينة ولوح", "kitchen"),
      i("مصفاة وعلب حفظ", "housewares"),
      i("فوط وإسفنج", "cleaning"),
      i("أكياس قمامة ومناديل", "grocery"),
      i("منظفات ومعطر", "cleaning"),
      i("ورق مطبخ وفويل واسترتش", "grocery"),
      i("أكياس فريزر", "grocery"),
      i("مناديل حمام", "grocery"),
      i("شاي وقهوة أول أسبوع", "grocery"),
      i("عدة طوارئ وخياطة", "tools"),
    ],
  },
  {
    id: "first-30",
    phase: "أول بيت",
    title: "بوكس أول 30 يوم",
    blurb: "ستارتر المونة والتنظيف والحمام والمطبخ — مش تشتري البيت كله تاني.",
    items: [
      i("ستارتر مونة", "grocery"),
      i("ستارتر تنظيف", "cleaning"),
      i("ستارتر حمّام", "bathroom"),
      i("ستارتر مطبخ يومي", "kitchen"),
      i("ستارتر قهوة", "grocery"),
      i("ستارتر شاي", "grocery"),
      i("ستارتر غسيل", "cleaning"),
      i("عناية شخصية يومية", "beauty"),
      i("عدة طوارئ", "tools"),
      i("عدد يدوية بسيطة", "tools"),
      i("بطاريات ولمبات", "tools"),
      i("مشتركات وإطالة", "tools"),
      i("إسعافات أولية", "tools"),
      i("علبة خياطة", "tools"),
    ],
  },
  {
    id: "kitchen-core",
    phase: "مطبخ",
    title: "جهاز المطبخ",
    blurb: "حلل وطاسات وتقديم — العمود الفقري لجهاز العروسة.",
    items: [
      i("حلل", "kitchen"),
      i("طاسات", "kitchen"),
      i("صواني", "kitchen"),
      i("طواجن", "kitchen"),
      i("حلة ضغط", "kitchen", "should"),
      i("كتل", "appliances"),
      i("طقم معالق وشوك وسكاكين", "kitchen"),
      i("أطباق وبولات", "kitchen"),
      i("أكواب ومجات وكاسات", "kitchen"),
      i("فناجين وطقم شاي وقهوة", "kitchen"),
      i("طقم تقديم وصواني تقديم", "kitchen"),
      i("برطمانات وعلب تخزين", "storage"),
      i("علب توابل وزجاجات زيت", "storage"),
      i("منظمات أدراج وثلاجة ومطبخ", "storage"),
      i("سلة فاكهة وخبز", "housewares"),
      i("حامل مناديل وتوابل", "housewares"),
      i("لوح تقطيع ومصفاة ومبشرة", "housewares"),
      i("فتاحة علب وزجاجات وعصارة", "housewares"),
      i("هراسة ومضرب يدوي ومقص مطبخ", "housewares"),
      i("ميزان مطبخ", "housewares", "should"),
      i("قوالب وأدوات حلويات", "housewares", "should"),
      i("أدوات قهوة وشاي", "kitchen", "should"),
    ],
  },
  {
    id: "gadgets",
    phase: "مطبخ",
    title: "رفايع المطبخ الدقيقة",
    blurb: "الفرصة الحقيقية في السلة الصغيرة: عصارة ثوم، مقشرة، ملاقط…",
    items: [
      i("عصارة ثوم", "housewares"),
      i("قطاع تفاح", "housewares", "should"),
      i("فاصل بيض", "housewares", "nice"),
      i("قطاع بيتزا", "housewares"),
      i("عصارة ليمون", "housewares"),
      i("مقشرة", "housewares"),
      i("مبشرة قشر", "housewares"),
      i("فتاحة علب", "housewares"),
      i("فتاحة زجاجات", "housewares"),
      i("صينية ثلج", "housewares"),
      i("قمع", "housewares"),
      i("أكواب قياس", "housewares"),
      i("ملاعق قياس", "housewares"),
      i("ملقاط مطبخ", "housewares"),
      i("سباتولا سيليكون", "housewares"),
      i("مضرب بيض", "housewares"),
      i("فرشة حلويات / زيت", "housewares"),
      i("مقص مطبخ", "housewares"),
      i("كلبسات أكياس", "housewares"),
      i("حامل عيدان أسنان", "housewares", "nice"),
      i("مسند معلقة", "housewares"),
      i("ماسك حلل وجوانتي فرن", "housewares"),
      i("مريلة", "housewares", "should"),
      i("رف تجفيف أطباق", "housewares"),
      i("منظم حوض وإسفنج", "housewares"),
      i("موزّع صابون مطبخ", "housewares"),
    ],
  },
  {
    id: "appliances-core",
    phase: "أجهزة",
    title: "أجهزة أساسية",
    blurb: "عبدالعزيز والماركتبليس — الأسعار تقدير تخطيط لحد ما يتربط فيد.",
    items: [
      i("ثلاجة", "appliances"),
      i("غسالة", "appliances"),
      i("بوتاجاز", "appliances"),
      i("فرن", "appliances", "should"),
      i("شفاط", "appliances"),
      i("تكييف", "appliances"),
      i("سخان", "appliances"),
      i("تلفزيون", "appliances", "should"),
    ],
  },
  {
    id: "small-appliances",
    phase: "أجهزة",
    title: "أجهزة صغيرة",
    blurb: "إير فراير وخلاط ومكنسة — سلة سريعة بعد الأجهزة الكبيرة.",
    items: [
      i("إير فراير", "appliances", "should"),
      i("ميكروويف", "appliances"),
      i("خلاط", "appliances"),
      i("محضّر طعام", "appliances", "should"),
      i("عجان / ميكسر", "appliances", "nice"),
      i("هاند بلندر", "appliances"),
      i("ماكينة قهوة", "appliances", "should"),
      i("كتل كهربا", "appliances"),
      i("ساندوتش ميكر", "appliances", "should"),
      i("شواية", "appliances", "nice"),
      i("توستر", "appliances", "should"),
      i("عصّارة", "appliances", "should"),
      i("شوبّر", "appliances"),
      i("قدّارة رز", "appliances", "nice"),
      i("مكنسة", "appliances"),
      i("ممسحة بخار", "appliances", "nice"),
      i("مكواة", "appliances"),
      i("سشوار", "appliances"),
    ],
  },
  {
    id: "cleaning-kit",
    phase: "تنظيف",
    title: "التنظيف والغسيل",
    blurb: "من المكنسة للمنظف — ستارتر البيت النضيف.",
    items: [
      i("مكنسة كهربا", "appliances"),
      i("ممسحة وجردل", "cleaning"),
      i("مكنسة يد وباج", "cleaning"),
      i("فرش تنظيف", "cleaning"),
      i("فوطة ميكروفايبر", "cleaning"),
      i("منظف زجاج وأرضيات", "cleaning"),
      i("منظف حمّام ومطبخ", "cleaning"),
      i("مطهّر", "cleaning"),
      i("مسحوق غسيل ومنعم", "grocery"),
      i("مزيل بقع ومبيض", "cleaning"),
      i("أكياس قمامة", "grocery"),
      i("سلال تخزين", "storage"),
      i("منشر غسيل", "storage"),
      i("شماعات", "storage"),
      i("لوح كي ومكواة", "appliances"),
    ],
  },
  {
    id: "bride-wardrobe",
    phase: "لبس",
    title: "لبس العروسة بالتفصيل",
    blurb: "من اللانجري لشوز الشغل — دولاب يبدأ البيت.",
    items: [
      i("لانجري", "lingerie"),
      i("بيجامات", "lingerie"),
      i("هوم وير", "lingerie"),
      i("روب", "lingerie"),
      i("نايت جاون", "lingerie", "should"),
      i("ملابس داخلية", "lingerie"),
      i("شرابات", "lingerie"),
      i("ملابس خروج", "fashion"),
      i("ملابس شغل", "fashion"),
      i("ملابس رياضية", "fashion", "should"),
      i("ملابس بحر", "fashion"),
      i("شباشب", "fashion"),
      i("أحذية وكوتشيات وصنادل", "fashion"),
      i("شنط وحقيبة يد", "fashion"),
      i("محفظة", "fashion"),
      i("إكسسوار", "fashion"),
      i("ساعات", "fashion", "should"),
      i("نظارة شمس", "fashion", "should"),
    ],
  },
  {
    id: "beauty-tools",
    phase: "تجميل",
    title: "تجميل وأدوات",
    blurb: "مكياج، عناية، سشوار، فرش، منظمات التسريحة.",
    items: [
      i("مكياج", "beauty"),
      i("عناية بشرة", "beauty"),
      i("عناية شعر", "beauty"),
      i("عناية جسم", "beauty"),
      i("عطر", "beauty"),
      i("مزيل عرق وبودي ميست", "beauty"),
      i("واقي شمس", "beauty"),
      i("سشوار", "appliances"),
      i("مكواة فرد", "appliances", "should"),
      i("مكواة تجعيد", "appliances", "should"),
      i("إبيلاتور", "beauty", "should"),
      i("أدوات منيكر", "beauty"),
      i("فرش مكياج", "beauty"),
      i("منظم مكياج وتسريحة", "storage"),
      i("مرايات", "beauty"),
    ],
  },
  {
    id: "bridal-gowns",
    phase: "يوم الفرح",
    title: "فساتين وبدلة",
    blurb: "شراء أو تأجير — بنوجّه للأحياء والبوتيكات.",
    items: [
      i("فساتين زفاف", "bridal"),
      i("فساتين خطوبة", "bridal"),
      i("فساتين سواريه", "bridal", "should"),
      i("بدلات العريس", "fashion"),
      i("تأجير فساتين", "bridal", "should"),
      i("تأجير بدلات", "fashion", "should"),
      i("تعديل وخياطة", "fashion"),
      i("تفصيل فساتين", "bridal", "nice"),
    ],
  },
  {
    id: "micro-kitchen",
    phase: "مطبخ",
    title: "رفايع المطبخ الصغيرة",
    blurb: "AOV عالي لو اتجمعت في بوكس.",
    items: [
      i("عصّارة ثوم", "housewares"),
      i("قطاعة تفاح / بيتزا", "housewares", "should"),
      i("فاصل بيض ومؤقت", "housewares", "nice"),
      i("فتاحة علب وزجاجات", "housewares"),
      i("مقشرة ومبشرة ليمون", "housewares"),
      i("مقص أعشاب ومطبخ", "housewares"),
      i("صينية ثلج وقوالب سيليكون", "housewares", "should"),
      i("أكواب وملاعق قياس", "housewares"),
      i("قمع وموزّع زيت", "housewares"),
      i("طبق زبدة وحامل موز", "housewares", "nice"),
      i("كلبسات أكياس وميزان", "housewares"),
    ],
  },
  {
    id: "pantry",
    phase: "تنظيم",
    title: "تنظيم المونة والثلاجة",
    blurb: "سوق لوحده: برطمانات وعلب ومنظمات.",
    items: [
      i("برطمانات توابل ورف", "storage"),
      i("علب رز وسكر ودقيق", "storage"),
      i("علب مكرونة وحبوب", "storage"),
      i("برطمان قهوة وشاي", "storage"),
      i("زجاجات زيت وخل", "kitchen"),
      i("منظم ثلاجة وفريزر", "storage"),
      i("حامل بيض ومعلبات", "storage"),
      i("سلال خضار وفاكهة", "storage"),
      i("ملصقات وأكياس", "storage"),
    ],
  },
  {
    id: "laundry",
    phase: "تنظيف",
    title: "ركن الغسيل",
    blurb: "سلة، منشر، مكواة، شماعات.",
    items: [
      i("سلة غسيل وفرّاز", "bathroom"),
      i("منشر غسيل", "storage"),
      i("شماعات وملاقط", "storage"),
      i("مكواة ولوح", "appliances"),
      i("كواية بخار", "appliances", "nice"),
      i("مشط كتان ورولر", "cleaning"),
      i("أكياس غسيل", "storage"),
      i("منظم مسحوق", "storage"),
    ],
  },
  {
    id: "bath-detail",
    phase: "حمام",
    title: "الحمام بالتفصيل",
    blurb: "من الستارة للروب.",
    items: [
      i("رف شاور وموزّع شامبو", "bathroom"),
      i("حامل صابون وفرش أسنان", "bathroom"),
      i("فرشة تواليت وحامل مناديل", "bathroom"),
      i("علاقة فوط ودواسة وستارة", "bathroom"),
      i("سلة مهملات وسلة غسيل", "bathroom"),
      i("منظم مستحضرات وأدوات شعر", "storage"),
      i("مراية مكبرة", "bathroom", "should"),
      i("فوط جسم ويد ووش وشعر", "bathroom"),
      i("روب وشباشب", "lingerie"),
    ],
  },
  {
    id: "bedroom",
    phase: "غرف",
    title: "غرفة النوم",
    blurb: "مفروشات + تنظيم الدولاب.",
    items: [
      i("واقي مرتبة ومخدة", "bedding"),
      i("مخدات وكيس مخدة", "bedding"),
      i("ملايات ولحاف وكفر", "bedding"),
      i("بطانية ومفرش", "bedding"),
      i("كوشنز وأباجورة", "decor", "should"),
      i("منبه", "smart", "nice"),
      i("منظم مجوهرات ومكياج", "storage"),
      i("منظم دولاب وأحذية", "storage"),
      i("تخزين تحت السرير", "storage", "should"),
      i("سرير ومرتبة", "furniture"),
      i("ملايات احتياطي", "bedding"),
      i("كفرات وبطاطين ولحاف", "bedding"),
      i("واقي مرتبة وكفر مخدة", "bedding"),
      i("فوط شعر وروب", "bathroom"),
      i("شماعات ومنظم أحذية ودولاب", "storage"),
      i("منظم أدراج وسلة غسيل", "storage"),
      i("كراتين تخزين وأكياس تفريغ", "storage"),
    ],
  },
  {
    id: "living",
    phase: "غرف",
    title: "المعيشة",
    blurb: "كنب وطاولة وتلفزيون وديكور.",
    items: [
      i("كنب وكراسي", "furniture"),
      i("ترابيزة ووحدات جانبية", "furniture"),
      i("وحدة شاشة", "furniture"),
      i("سجاد وستائر", "bedding"),
      i("كوشنز وthrows", "decor"),
      i("نجف وأباجورات", "decor"),
      i("مرايات وبراويز وفازات", "decor"),
      i("شموع وديفيوزر", "decor"),
      i("سجاد وستائر", "bedding"),
      i("نباتات ومرايات وورد جدار", "decor", "should"),
      i("ساعات حائط", "decor", "nice"),
      i("أبجور أرضي وطاولة", "decor", "should"),
    ],
  },
  {
    id: "dining",
    phase: "غرف",
    title: "السفرة",
    blurb: "ترابيزة + تقديم كامل.",
    items: [
      i("سفرة وكراسي", "furniture"),
      i("مفرش ورانر وبلايس مات", "bedding"),
      i("مناديل سفرة", "housewares", "should"),
      i("أطباق وبولات ومعالق", "kitchen"),
      i("صواني تقديم وبولة سلطة", "kitchen"),
      i("حامل تورتة وسكينة", "kitchen", "nice"),
      i("طقم شاي وقهوة", "kitchen"),
      i("إبريق وكاسات وكوسترات", "kitchen"),
    ],
  },
  {
    id: "toolkit",
    phase: "عدة",
    title: "عدة البيت",
    blurb: "اللي بيتنسي لحد ما تحتاجي مسمار.",
    items: [
      i("طقم مفكات ومطرقة وزرادية", "tools"),
      i("متر وقطاعة ومقص", "tools"),
      i("مفاتيح ألن ومسامير", "tools"),
      i("خطافات وغراء ولزق", "tools"),
      i("شريط كهربا ومشترك", "tools"),
      i("كشاف وبطاريات ولمبات", "tools"),
      i("علبة خياطة", "tools", "should"),
    ],
  },
  {
    id: "smart-home",
    phase: "بيت ذكي",
    title: "البيت الذكي",
    blurb: "لمبات وبلج وكاميرات لو المنصة حديثة.",
    items: [
      i("لمبات ومفاتيح ذكية", "smart", "should"),
      i("كاميرات وجرس فيديو", "smart", "nice"),
      i("سماعة ذكية", "smart", "nice"),
      i("مكنسة روبوت", "appliances", "nice"),
      i("ميزان هوا ومنقّي هواء", "smart", "nice"),
      i("كتل قهوة ذكي", "smart", "nice"),
      i("لمبات ذكية", "smart", "should"),
      i("بلج ذكي", "smart", "should"),
      i("كاميرات ذكية", "smart", "nice"),
      i("جرس فيديو", "smart", "nice"),
      i("كالون ذكي", "smart", "nice"),
      i("حساسات حركة", "smart", "nice"),
      i("مقوّي واي فاي", "smart", "should"),
      i("سماعة ذكية", "smart", "nice"),
      i("شرائط LED", "smart", "should"),
      i("إكسسوار سمارت TV", "smart", "nice"),
      i("شاحن USB ومشتركات", "tools"),
      i("إدارة كابلات", "storage", "should"),
    ],
  },
  {
    id: "fragrance",
    phase: "ديكور",
    title: "عطور البيت",
    blurb: "شموع وبخور وديفيوزر.",
    items: [
      i("شموع معطرة", "decor"),
      i("عيدان / ديفيوزر كهربا", "decor"),
      i("بخاخ جو ومفروشات", "cleaning"),
      i("معطر دولاب", "decor", "should"),
      i("بخور وعطور زيت", "faith"),
    ],
  },
  {
    id: "personalized",
    phase: "هدايا",
    title: "منتجات باسمين",
    blurb: "طلبات مخصّصة — تطريز وحفر.",
    items: [
      i("فوط وروبات باسم", "gifts", "nice"),
      i("مجات وأطباق باسم", "gifts", "nice"),
      i("إطار فرح ولافتة اسم", "gifts", "should"),
      i("بيجامات زوجين", "lingerie", "nice"),
      i("شنط شهر عسل مطرّزة", "travel", "nice"),
    ],
  },
  {
    id: "faith",
    phase: "أول بيت",
    title: "ركن الصلاة",
    blurb: "سجاد ومصحف وبخور.",
    items: [
      i("سجادات صلاة", "faith"),
      i("مصحف وحامل", "faith"),
      i("سبحة وبوكس صلاة", "faith", "should"),
      i("لوحات آيات", "faith", "nice"),
    ],
  },
  {
    id: "pets",
    phase: "بعد الجواز",
    title: "لو عندكم حيوان",
    blurb: "اختياري — مش جزء من كل جهاز.",
    items: [
      i("سرير أليف", "gifts", "nice"),
      i("أطباق أكل ونافورة", "gifts", "nice"),
      i("صندوق رمل وحامل سفر", "gifts", "nice"),
      i("ألعاب وأدوات تهذيب", "gifts", "nice"),
    ],
  },
  {
    id: "baby",
    phase: "بعد الجواز",
    title: "تجهيز المستقبل",
    blurb: "بعد الجواز، مش أول يوم.",
    items: [
      i("لبس ومفروشات بيبي", "gifts", "nice"),
      i("حمام وإرضاع", "gifts", "nice"),
      i("عربية ومقعد سيارة", "gifts", "nice"),
      i("مونيتور وألعاب", "gifts", "nice"),
      i("أثاث غرفة أطفال", "furniture", "nice"),
    ],
  },
  {
    id: "grocery",
    phase: "أول بيت",
    title: "بقالة أول شهر",
    blurb: "رز وزيت ومنظفات من الهايبر.",
    items: [
      i("رز ومكرونة ودقيق", "grocery"),
      i("سكر وملح وزيت وسمنة", "grocery"),
      i("شاي وقهوة ونسكافيه", "grocery"),
      i("توابل وصلصة وبقول", "grocery"),
      i("مياه ومناديل", "grocery"),
      i("مسحوق ومنعم وصابون وشامبو", "grocery"),
    ],
  },
  {
    id: "wedding-services",
    phase: "خدمات الفرح",
    title: "خدمات قبل الجواز ويوم الفرح",
    blurb: "قاعة، مصور، ميكب، زفة — بنوجّه للأحياء، مش حجز من وفّري.",
    items: [
      i("قاعة أفراح", "services"),
      i("منظّمة فرح / بلانر", "services", "should"),
      i("حفلة خطوبة", "services", "should"),
      i("تصوير فوتوسيشن", "services"),
      i("تصوير فيديو فرح", "services"),
      i("ميكب آرتست", "services"),
      i("هير ستايلست", "services"),
      i("نيل آرتست", "services", "should"),
      i("حنة", "services", "should"),
      i("تأجير فستان / بدلة", "bridal", "should"),
      i("تعديل وخياطة", "fashion", "should"),
      i("دعوات رقمية ومطبوعة", "gifts"),
      i("توزيعات وهدايا مدعوين", "gifts"),
      i("ورد وبوكيه", "gifts"),
      i("كوشة وإضاءة", "services"),
      i("DJ / فرقة / ساوند", "services"),
      i("زفة وسيارة فرح", "services", "should"),
      i("تسلية أطفال في القاعة", "services", "nice"),
      i("ديكور وورد", "gifts"),
      i("بوكيه العروسة", "gifts"),
      i("كروت وبوكسات دعوة", "gifts"),
      i("توزيعات / wedding favors", "gifts"),
    ],
  },
  {
    id: "home-install",
    phase: "خدمات البيت",
    title: "خدمات بعد شراء الجهاز",
    blurb: "تركيب وصيانة ونقل — المنصة تربط مش بتتنفّذ بنفسها.",
    items: [
      i("تركيب تكييف وسخان", "home-services"),
      i("تركيب أجهزة", "home-services"),
      i("صيانة أجهزة", "home-services", "should"),
      i("سباكة وكهربا", "home-services"),
      i("نجارة وألوميتال", "home-services", "should"),
      i("تفصيل ستائر ومطبخ ودولاب", "home-services", "should"),
      i("نقل ورفع عفش", "home-services"),
      i("تنظيف قبل السكن / ديب كلينينج", "home-services"),
      i("مكافحة حشرات", "home-services", "should"),
      i("تركيب إضاءة وكاميرات وسمارت هوم", "home-services", "nice"),
    ],
  },
  {
    id: "gifts-detail",
    phase: "هدايا",
    title: "هدايا العروسة والزوجين",
    blurb: "بوكسات جاهزة + تخصيص الاسم والتاريخ.",
    items: [
      i("بوكس عروسة / سيلف كير", "gifts"),
      i("بوكس عطر ومكياج", "gifts"),
      i("روب وفوطة باسم", "gifts", "should"),
      i("مج وإطار باسمين", "gifts", "should"),
      i("ألبوم فرح ولافتة اسم", "gifts"),
      i("بطانية ومخدات زوجين", "gifts", "nice"),
      i("حفر وتطريز وتاريخ الجواز", "gifts", "nice"),
      i("هدايا للعروسة: مجوهرات وبوكس عطر", "gifts"),
      i("هدايا للزوجين: براويز وأساور", "gifts", "should"),
    ],
  },
];

export const fiveArcs = [
  "قبل الجواز",
  "يوم الجواز",
  "تجهيز البيت",
  "أول شهر",
  "بعد الجواز",
] as const;

export type FiveArc = (typeof fiveArcs)[number];

const ARC_BY_GROUP: Record<string, FiveArc> = {
  engagement: "قبل الجواز",
  "wedding-services": "قبل الجواز",
  "wedding-day": "يوم الجواز",
  memories: "يوم الجواز",
  "beauty-box": "قبل الجواز",
  "nail-tools": "قبل الجواز",
  wardrobe: "قبل الجواز",
  honeymoon: "قبل الجواز",
  "first-week": "أول شهر",
  grocery: "أول شهر",
  "micro-kitchen": "تجهيز البيت",
  pantry: "تجهيز البيت",
  laundry: "تجهيز البيت",
  "bath-detail": "تجهيز البيت",
  bedroom: "تجهيز البيت",
  living: "تجهيز البيت",
  dining: "تجهيز البيت",
  toolkit: "أول شهر",
  "smart-home": "تجهيز البيت",
  fragrance: "تجهيز البيت",
  personalized: "قبل الجواز",
  "gifts-detail": "قبل الجواز",
  faith: "تجهيز البيت",
  pets: "بعد الجواز",
  baby: "بعد الجواز",
  "home-install": "بعد الجواز",
  "first-30": "أول شهر",
  "kitchen-core": "تجهيز البيت",
  gadgets: "تجهيز البيت",
  "appliances-core": "تجهيز البيت",
  "small-appliances": "تجهيز البيت",
  "cleaning-kit": "تجهيز البيت",
  "bride-wardrobe": "قبل الجواز",
  "beauty-tools": "قبل الجواز",
  "bridal-gowns": "يوم الجواز",
};

export function arcOf(groupId: string): FiveArc {
  return ARC_BY_GROUP[groupId] ?? "تجهيز البيت";
}

export const lifePhases = [...new Set(needGroups.map((g) => g.phase))];

export const needItemCount = needGroups.reduce((n, g) => n + g.items.length, 0);

export function searchNeeds(q: string): { group: NeedGroup; items: NeedItem[] }[] {
  const raw = q.trim();
  return needGroups
    .map((group) => ({
      group,
      items: raw
        ? group.items.filter(
            (it) =>
              arabicIncludes(it.name, raw) ||
              arabicIncludes(group.title, raw) ||
              arabicIncludes(group.phase, raw) ||
              arabicIncludes(arcOf(group.id), raw),
          )
        : group.items,
    }))
    .filter((row) => row.items.length);
}

export function itemsForArc(arc: FiveArc): NeedItem[] {
  return needGroups.filter((g) => arcOf(g.id) === arc).flatMap((g) => g.items);
}

export function needsForSources(sourceIds: string[], pri?: NeedPri): NeedItem[] {
  const set = new Set(sourceIds);
  return needGroups.flatMap((g) =>
    g.items.filter((it) => set.has(it.source) && (!pri || it.pri === pri)),
  );
}
