/** SKUs that have a dedicated product photo under public/product-photos. */
export const UNIQUE_PHOTO_IDS = new Set([
  "bath-towels-8",
  "bedroom-oak",
  "beko-washer-7",
  "bosch-dishwasher",
  "braun-mixer",
  "bridal-abaya",
  "bridal-dress",
  "bride-slippers",
  "carrier-ac-225",
  "cotton-duvet",
  "cotton-pajamas",
  "crystal-chandelier",
  "dining-6",
  "evening-bag",
  "fresh-freezer-5",
  "fresh-heater",
  "gree-ac-15",
  "hoover-vacuum",
  "kenwood-mixer",
  "kettle-kenwood",
  "kids-pajamas",
  "kitchen-linens",
  "lattafa-perfume",
  "lg-tv-55",
  "lg-washer-10",
  "lg-washer-8",
  "men-galabiya",
  "philips-airfryer",
  "remington-dryer",
  "robot-vacuum-tuya",
  "samsung-fridge-18",
  "samsung-soundbar",
  "sharp-ac-15",
  "tefal-iron",
  "tefal-pots",
  "tornado-fan-18",
  "toshiba-fridge-16",
  "toshiba-microwave",
  "towel-set",
  "unionaire-stove",
  "velvet-sofa",
  "water-dispenser-fresh",
  "women-galabiya",
  "zircon-set",
]);

export function uniquePhotoSrc(id: string) {
  return UNIQUE_PHOTO_IDS.has(id) ? `/product-photos/${id}.jpg` : "";
}
